### PR TITLE
Fixes #1423 - fixes build badge in docs

### LINKED ISSUE #1423: Fix build badge in the docs
Screen Shot 2022-09-29 at 11 35 26 AM

### PR DESCRIPTION
**Pull request by jackiekazil**
Fixes #1423 - fixes build badge in docs & updates other badges.

### CODE REVIEW

**Comment by rht** [comment]
The commit message needs to start with imperative voice for consistency, since we put Tim Pope's guideline now.

**Comment by rht** [comment]
The pre-commit error is not a blocker, however.

**Comment by jackiekazil** [comment]
@rht fixed ... I think. English is not my first language - so feel free to let me know if I didn't capture it right.

**Comment by rht** [comment]
No worries, it looks good now.

**Pull request merged**
