### PR TITLE
Tutorial improvement

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by rht** [comment]
I'm progressively creating multiple PRs for this:
- [ ] Switch to Seaborn #1718

Sections to be ported:
- [ ] "You can also plot a reporter of multiple agents over time."
- [ ] "Read the model data from the CSV file"
- [ ] "Additional agent reporter"
- [ ] "We can create differnt kinds of plot from"
- [ ] "Analyzing model reporters: Comparing 5 scenarios"
- [ ] "Analyzing agent reporters"
- [ ] "Calculate the mean of the wealth"

**Comment by tpike3** [comment]
> I'm progressively creating multiple PRs for this:
> 
> * [ ]  Switch to Seaborn [intro tutorial: Switch to using Seaborn #1718](https://github.com/projectmesa/mesa/pull/1718)
> 
> Sections to be ported:
> 
> * [ ]  "You can also plot a reporter of multiple agents over time."
> * [ ]  "Read the model data from the CSV file"
> * [ ]  "Additional agent reporter"
> * [ ]  "We can create differnt kinds of plot from"
> * [ ]  "Analyzing model reporters: Comparing 5 scenarios"
> * [ ]  "Analyzing agent reporters"
> * [ ]  "Calculate the mean of the wealth"

I am tracking you are still working some of these, so it is not yet ready. Is that correct?

**Comment by rht** [comment]
Yes, I haven't worked on them yet.

**Comment by tpike3** [comment]
@rht -- 
- Do you want this to be part of 2.0?
- If yes, do you want co-authors to help knock out some of the tasks or no?

**Comment by rht** [comment]
This is not a blocker to 2.0 / it's optional, given that the blocker ones are the breaking changes ones. But yeah, I'd appreciate if you want to pick up the tasks in the list.

**Comment by EwoutH** [comment]
What are we going to do with this PR? I think it's nice to get some tutorial improvements in 2.2.0.

**Comment by EwoutH** [comment]
With #1955 merged, I think we can close this right?

**Comment by rht** [comment]
Does #1955 contain everything in this PR? It was so much easier to review with the smaller diff and the RTD.

**Pull request closed without merging**
