### PR TITLE
Move core example models back (v2)

### PR DESCRIPTION
**Pull request by EwoutH**
This PR moves several core examples back to the main Mesa repository, organized into **Basic** and **Advanced** categories:

**Basic Examples:**
- Boltzmann Wealth
- Boid Flockers
- Conway's Game of Life
- Virus on Network
- Schelling Segregation

**Advanced Examples:**
- Epstein Civil Violence
- Sugarscape with Traders
- Wolf-Sheep Predation
- Demographic Prisoner's Dilemma on Grid

It uses some ideas discussed in https://github.com/projectmesa/mesa/discussions/2330#discussioncomment-10922651, and the division of models originates from https://github.com/projectmesa/mesa/pull/2349#issuecomment-2408945055.

It keeps the git history, with the only side effect that the PR numbers now link to the wrong repo (there's no easy way to fix this).

Moving these examples back into the main Mesa repository:
- Allows opening PRs that show how both code and models change in tandem
- Removes the need for two PRs for each feature (but still allows it)
- Simplifies version control, ensuring each example works with the exact commit/release of Mesa
- Enables more comprehensive testing of these examples within our CI pipeline, including batch runs and visualizations
- These diverse, high-quality examples will directly help users test a model after installing Mesa.

After this PR is merged, these examples can be updated further to become fully exemplary.

@projectmesa/maintainers, like with the previous PR, I kindly request your review.

### CODE REVIEW

**Review by quaquel — APPROVED** [review]
changes look good. 

I guess all the requirements.txt files can be removed since from now on these will be up to date?

**Comment by EwoutH** [comment]
Thanks!

> I guess all the requirements.txt files can be removed since from now on these will be up to date?

Yes, I will open a tracking issues with things that can be improved / cleaned up, and try to tick as many of boxes feasible once this is merged.

**Comment by Corvince** [comment]
Approved the PR itself, but not sure if all the discussion points from v1 have been resolved?

**Review by Corvince — APPROVED** [review]

**Comment by EwoutH** [comment]
Thanks!

> but not sure if all the discussion points from v1 have been resolved?

Define resolved ;)

Full consensus among 7 maintainer (on very little detail)? No. Majority agrees on major points? Yes. Clear plan to move forward? I also believe so.

But yeah, I would like to get a little more alignment in today’s meeting.

**Comment by EwoutH** [comment]
@tpike3 @jackiekazil we discussed it in the meeting, but could you give your formal approval, mainly for historical reference?

**Review by tpike3 — APPROVED** [review]
Per 15 Oct Dev session I agree

**Comment by EwoutH** [comment]
With jackie also in approval in the meeting, we have 5 core maintainers in agreement.

Thanks for the quick and insightful discussion everyone!

**Comment by EwoutH** [comment]
The big checklist to start working on:
- https://github.com/projectmesa/mesa/issues/2364

**Pull request merged**
