### PR TITLE
Update version to 2.3.0-dev, add 2.2.2 release notes

### PR DESCRIPTION
**Pull request by EwoutH**
Two small maintenance changes:
- Update the version in `__init__.py` to `"2.3.0-dev"`
- Add the 2.2.2 release notes to the main changelog

### CODE REVIEW

**Review by rht — APPROVED** [review]

**Comment by rht** [comment]
What should be the minimum number of maintainer's approval for a release-related PR? I'd say at least 2.

**Comment by EwoutH** [comment]
Do we include the maintainer that approved the PR?

Nice to see the performance benchmark bot working so dedicatedly. Maybe it doesn't need to run on _every_ PR.

**Comment by EwoutH** [comment]
pre-commit.ci autofix

**Comment by quaquel** [comment]
would it be possible to merge #1984 before this as well (would help me with an exam)

**Comment by EwoutH** [comment]
Already released 2.2.2, this is just a backport of the release notes to main.

We can do a 2.2.3 release if needed.

**Pull request merged**
