### PR TITLE
Cleanup and restructure EpsteinCivilViolence and PdGrid examples

### PR DESCRIPTION
**Pull request by EwoutH**
Cleanup and restructure the EpsteinCivilViolence and PdGrid advanced example models. This PR is similar to what was done in the basic examples in https://github.com/projectmesa/mesa/pull/2365.

It draws the discrete spaces as was supported in https://github.com/projectmesa/mesa/pull/2386 and updates the imports to be absolute, similar to https://github.com/projectmesa/mesa/pull/2402.

EpsteinCivilViolence and PdGrid now:
- Have all their Agent code in an `agents.py` file.
- Use a flat structure.
- Use the newest SolaraViz API
- Have the old visualization code removed

Screenshot_522
Screenshot_523

A few things to note:
- Handeling agent_portrayals is still finicky
- I couldn't get the square shape to work
- EpsteinCivilViolence shows remarkable stable behavior. Is this correct?
- Claude 3.5 Sonnet went full YOLO and found a way to get a choice selector to work:
    ```Python
    "activation_order": {
        "type": "Select",
        "value": "Random",
        "values": PdGrid.activation_regimes,
        "label": "Activation Regime"
    }
    ```
    @Corvince Is this a proper approach? If so, does that mean that #2376 isn't needed anymore?
- Real interesting changes in behavior between the random, sequential and staged activation regimes! Sequential and staged quickly go to all cooperating or all non-cooperating. Maybe we should double check if this works as intended.

### CODE REVIEW

**Comment by quaquel** [comment]
The code reorganization etc. looks fine from my end, so I'll approve the PR on that ground. 

> EpsteinCivilViolence shows remarkable stable behavior. Is this correct?

Luckily for you, I wasted an entire morning on this for my teaching version of this model on this question: swap out OrthogonalMooreGrid for OrthogonalVonNeumann grid. There are a few more things I would like to do with this example (but those can wait for a separate PR). 


> Real interesting changes in behavior between the random, sequential and staged activation regimes! Sequential and staged quickly go to all cooperating or all non-cooperating. Maybe we should double check if this works as intended.

I plan to do a pr on this soon based on an mesa 3.0 updated version of [my teaching version](https://github.com/quaquel/EPA123a_open/blob/master/src/week_3/Assignment%202%20model%20answer.ipynb). It might be nice to include the activation order as a user input in the gui version. It would not be strange if activation order matters a lot in this model.

**Review by quaquel — APPROVED** [review]

**Comment by EwoutH** [comment]
@quaquel merged, go ahead and follow up with changing the OrthogonalMooreGrid to OrthogonalVonNeumann. If you figured out why that mattered, would be very curious to hear that!

**Comment by EwoutH** [comment]
@quaquel so we don't forget it, should I create an issue for changing the OrthogonalMooreGrid to OrthogonalVonNeumann?

**Comment by quaquel** [comment]
Yes

**Pull request merged**
