### PR TITLE
Coalition Game Theory - Bilateral Shapley Value

### PR DESCRIPTION
**Pull request by tpike3**
I wrote up  a Bilateral Shapley value module, as well as the docs html build within the apis folder. This is my first attempt really at github and contributing so invariably I messed up stuff. Let me know what I need to fix.

I was able to get snowflake to work, but not nose and travis, so I think there are issues that I am not sure how to resolve. 

Please let me know. 

Vr, Tom Pike

### CODE REVIEW

**Comment by Corvince** [comment]
Hi Tom,

I am not a maintainer of mesa so I can not speak for the project, but I think your module is too specific to be merged into mesa. See the discussion on #360 . I think the latest idea was to have such models as an extension to mesa, but it is not clear yet how this should work. 

Regarding your travis build. I see no problem with nose there, but flake8 produces some errors and warnings. [The logs](https://travis-ci.org/projectmesa/mesa/jobs/293765210) should be self explanatory in line 630 - 637.
Please note that travis currently also fails until #414 is merged or otherwise resolved.

**Comment by tpike3** [comment]
Corvince: Thanks! Maybe a mesa.game_theory would be best. I will see what the maintainers say.  I am very flexible and just want to support. 

I did figure out nosetests (had to watch some videos to get the concept) and built a test module to see if it breaks if  either mesa or networkx gets updated. Based on this my module passes the test and shows no errors for flake8. I will wait to see what direction is desired, or if this module is even desired for MESA  and then update from there. 

Thanks again.

**Comment by jackiekazil** [comment]
Just to update this with our discussion... @tpike3 is going to break this off into a separate package, not in core Mesa. He is also working on guide on how to create packages that work with Mesa. More info ... https://github.com/projectmesa/mesa/issues/448

**Comment by jackiekazil** [comment]
@tpike3 ... let me know if I got something wrong with that. :-)

**Pull request closed without merging**
