### PR TITLE
Examples in external repo

### PR DESCRIPTION
**Pull request by SebastianoF**
Related to #134 .

The tests related to examples are integration tests leveraging on the examples, or examples tests itself. Should be moved under the mesa-examples repository. Skipped in the PR for now.

Thanks!
S

### CODE REVIEW

**Comment by SebastianoF** [comment]
Planning to recover the percentage lost with this PR in the week end!

**Comment by SebastianoF** [comment]
Hello!


https://github.com/projectmesa/mesa/issues/740
https://github.com/projectmesa/mesa/issues/741
https://github.com/projectmesa/mesa/issues/742

**Comment by rht** [comment]
There is a huge merge conflict in this PR. This PR should better be redone right after when the decision to move the examples to an external repo is finalized.

**Comment by SebastianoF** [comment]
Yep thanks, in the meantime I changed job twice and not really into mesa any longer. Closing it, and I am not likely to re-do the PR after the decision will be finalised.

**Pull request closed without merging**
