### PR TITLE
Fix Ruff errors and pin Ruff version

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by rht** [comment]
@wang-boyu we should pin the Ruff version in Mesa-Geo as well, so that we are not caught by unexpected new lint errors.

**Comment by wang-boyu** [comment]
> @wang-boyu we should pin the Ruff version in Mesa-Geo as well, so that we are not caught by unexpected new lint errors.

Sure, I'll look into it.

**Comment by tpike3** [comment]
Changes LGTM, but for the failing pre-commit.ci failure. Don't you need to commit the changes (trailing whitespace) that were made so pre-commit.ci passes (in this case) before merge. 

Can you also add messages for commit history on updates to main to fix cookiecutter and fixes to to barchart visualization.

**Comment by rht** [comment]
Whitespaces fixed.

> Can you also add messages for commit history on updates to main to fix cookiecutter and fixes to to barchart visualization.

This is not a release to bump the version to 1.2.1.

**Comment by tpike3** [comment]
LGTM

**Pull request merged**
