### PR TITLE
Correct get_heading for toroidal space

### PR DESCRIPTION
**Pull request by rht**
This is an improved version of #1664 where each dimension is optimized independently.

### CODE REVIEW

**Comment by jackiekazil** [comment]
LGTM

**Comment by EwoutH** [comment]
Did you measure performance on this PR? The `get_heading()` implementation in #1620 was almost twice as fast, but how fast is this one?

**Comment by EwoutH** [comment]
Also, why weren't the additional tests from #1620 included? Those tests where explicitly written to test and check the unintended behaviour we were trying to fix with this PR.

**Comment by rht** [comment]
This is based on the Agents.jl implementation https://github.com/projectmesa/mesa/discussions/1632#discussioncomment-5837207.

This has clearer logic than #1620, because each dimension is optimized separately.
The tests indeed should be updated.

**Pull request merged**
