### PR TITLE
solara: Implement decorator to simplify custom space drawer

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by rht** [comment]
@tpike3 this is a very convenient feature to have, and would be great to have it in before the 2.1.2 release.

**Comment by rht** [comment]
`solara.FigureMatplotlib(space_fig, dependencies=[viz.model, viz.df])` is a rather arcane line requiring people to understand Solara reactive component. With the indirection, people just need to focus on drawing Matplotlib.

**Comment by EwoutH** [comment]
@rht which direction would you like this PR to go?

**Comment by rht** [comment]
This PR is now obsolete. The current API is already simple enough to not require this wrapper.

**Pull request closed without merging**
