### PR TITLE
Add performance benchmarking scripts and run in CI

### PR DESCRIPTION
**Pull request by EwoutH**
_Let's see how many attempts this is going to take_

General usage (once this is merged to main):
1. Go to the main branch.
2. Run `global_benchmarks.py`
3. Go to your development branch
4. Run `global_benchmarks.py` again
5. Run `compare_timings.py`

It should output a table like this:

| Model          | Size   | Init time [95% CI]            | Run time [95% CI]         |
|----------------|--------|-------------------------------|---------------------------|
| SchellingModel | small  | 🔵 +5.7% [+1.7%, +10.8%]      | 🔵 +5.8% [+1.1%, +12.0%]  |
| SchellingModel | large  | 🔵 -1.0% [-2.1%, -0.2%]       | 🔵 -0.5% [-2.1%, +1.2%]   |
| WolfSheep      | small  | 🔵 +0.0% [-0.6%, +0.6%]       | 🔵 -0.0% [-0.5%, +0.4%]   |
| WolfSheep      | large  | 🔴 +211.2% [+172.4%, +255.0%] | 🔵 +4.6% [-8.0%, +22.4%]  |
| BoidFlockers   | small  | 🔵 +0.1% [-9.7%, +11.6%]      | 🔵 +3.1% [-0.7%, +7.4%]   |
| BoidFlockers   | large  | 🔵 -11.9% [-25.2%, -1.8%]     | 🟢 -18.2% [-31.6%, -4.7%] |

Positive indicates increate in runtime, negative a decrease.

### CODE REVIEW

**Comment by EwoutH** [comment]
(I'm truly sorry if someone set email notifications for "ready for review")

**Comment by Corvince** [comment]
I think there is a vscode extension that lets you run GitHub actions locally, maybe give it a try?

**Comment by Corvince** [comment]
> (I'm truly sorry if someone set email notifications for "ready for review")

I don't, but why are you doing this? To trigger GA actions?

**Comment by EwoutH** [comment]
Yes, and because I was both too lazy to built a better trigger and too optimistic about the amount of tries it was going to take.

**Comment by EwoutH** [comment]
@quaquel you can review the benchmark scripts if you want.

@jackiekazil or @tpike3 to get the CI working I need to create an access token with commenting permissions and add that as secret to the repo. I don't have the permissions for that. Could you help me out here? Preferably with a short videocall (I'm reachable on matrix).

**Comment by quaquel** [comment]
Are you relying on Python 3.12? Your format strings in lines 49 and 58 in global_benchmark.py use `"` both on the overall string and within the format string for the time formatting. If you change the latter to a single quoted string, it should also work on an older version.

**Comment by EwoutH** [comment]
> Are you relying on Python 3.12? 

I run 3.12 locally indeed. Good catch, fixed it.

**Comment by quaquel** [comment]
It looks great and started my first run while playing with the new grid stuff. 

I noticed that you rely on pickle to store results. Why, and can't we come up with a better solution? Pickle is very brittle and only really useful for short-term local storage. From a quick look at the code, it should be possible to just turn everything into a big dataframe and store it as a human-readable CSV?

**Comment by EwoutH** [comment]
> Why, and can't we come up with a better solution?

> Pickle is very brittle and only really useful for short-term local storage.

I know your pickle with pickle, but for me this is doesn't need to be saved longer than two minutes in my own, stable environment. It's literally short-term local storage :). The output table is the thing that counts at the end.

And to be honest I never have problems with pickles. I really like that you can throw any data in there that you want, which makes it great for fast development.

**Comment by Corvince** [comment]
> @quaquel you can review the benchmark scripts if you want.
> 
> @jackiekazil or @tpike3 to get the CI working I need to create an access token with commenting permissions and add that as secret to the repo. I don't have the permissions for that. Could you help me out here? Preferably with a short videocall (I'm reachable on matrix).

From my reading GITHUB_TOKEN that you seem to use should have that permission. Are you sure that's the problem?

**Comment by EwoutH** [comment]
Never been so happy to have seen something [fail so gracefully](https://github.com/projectmesa/mesa/actions/runs/7588524058/job/20671234420#step:12:76):

Screenshot_348

@jackiekazil or @tpike3 could you
- either resolve this error (create a new access token with comment permissions, add it as secret to GitHub, and replace `GITHUB_TOKEN` with the name of the new token (in [line 64](https://github.com/projectmesa/mesa/actions/runs/7588524058/workflow#L64), `github-token: ${{ secrets.GITHUB_TOKEN }}`)
- give me enough permissions to do it myself (I need to create tokens and modify secrets)

Resources
- https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment

**Comment by EwoutH** [comment]
> From my reading GITHUB_TOKEN that you seem to use should have that permission. Are you sure that's the problem?

Unfortunately, I'm 90% sure. The [error](https://github.com/projectmesa/mesa/actions/runs/7588649640/job/20671642093#step:12:32):
```
Error: Unhandled error: HttpError: Resource not accessible by integration
```
implies 
The error along with a 403 status code indicates a permissions issue. It most likely means that the GitHub token being used does not have the necessary permissions to create a comment on the issue or pull request.

**Comment by EwoutH** [comment]
Okay, there are a few minor things, like Black and ruff failing because the added benchmark models don't adhere to their standards, but the benchmark scripts are further ready. General usage (once this is merged to main):
1. Go to the main branch.
2. Run `global_benchmarks.py`
3. Go to your development branch
4. Run `global_benchmarks.py` again
5. Run `compare_timings.py`

It should output a table like this:

| Model          | Size   | Init time [95% CI]     | Run time [95% CI]    |
|:---------------|:-------|:-----------------------|:---------------------|
| SchellingModel | small  | -4.5% [-10.1%, -0.4%]  | +4.2% [+0.6%, +7.8%] |
| SchellingModel | large  | -7.7% [-20.5%, -0.6%]  | -2.0% [-3.7%, -0.3%] |
| WolfSheep      | small  | +34.8% [-5.1%, +90.3%] | +1.0% [-3.2%, +5.4%] |
| WolfSheep      | large  | +9.0% [+0.8%, +19.9%]  | +0.4% [-1.8%, +2.4%] |
| BoidFlockers   | small  | +1.0% [-0.4%, +3.1%]   | +0.8% [-0.2%, +1.8%] |
| BoidFlockers   | large  | +1.3% [+0.4%, +2.2%]   | +0.2% [-1.9%, +2.6%] |

Positive indicates increate in runtime, negative a decrease. I will add fancy emojis tomorrow to make it really clear if it's good, bad or insignificant.

**Comment by Corvince** [comment]
I think you can set the permission inside the workflow file similar to this

https://github.com/projectmesa/mesa/blob/main/.github%2Fworkflows%2Frelease.yml#L18-L20

**Comment by EwoutH** [comment]
According to ChatGPT it's something different:

> Adding the `id-token: write` permission in your GitHub Actions workflow will not resolve the issue you're experiencing with the "Resource not accessible by integration" error. The `id-token: write` permission is used to request an OIDC token for use with other services that understand OpenID Connect (OIDC) tokens, and it is unrelated to the permissions needed to comment on issues or pull requests in GitHub.

**Comment by Corvince** [comment]
That was just meant as an example. I would guess you need `pull-requests: write`

**Comment by Corvince** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

**Comment by EwoutH** [comment]
@Corvince Thanks for your insights. They're really useful.

I think I zoomed further in to the issue: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

Check the column "Maximum access for pull requests from public forked repositories". Everything is `read`, even if you define it explicitly.

I'm pulling this PR in from my own fork EwoutH/mesa. Many contributors will do that, so this workflow has to work from public forks. But I understand very clearly why it's disabled by default, otherwise anyone can open any PR and do anything.

So the solution stays the same as suggested [here](https://github.com/projectmesa/mesa/pull/1978#issuecomment-1901037499), we need to make a new very-specific, but permissive token with "pull-requests: write" access that only runs on this workflow and only is allowed to make pull request comments.

**Comment by EwoutH** [comment]
Weird stuff. Can't figure it out without access to tokens and secrets unfortunately. Will wait until I have the permissions.

**Comment by quaquel** [comment]
@EwoutH Do you mind if I commit to this branch with various minor updates?
- fix for < 3.12
- insertion of mesa into sys.path
- ruff related fixes

**Review by rht — APPROVED** [review]

**Comment by EwoutH** [comment]
Go ahead, and thanks for asking.

With #1979 merged I just wanted to rebase it on that PR, shall I do that first?

**Comment by EwoutH** [comment]
@quaquel with #1979 merged it actually easier to just open a new branch (and PR) from that. On this branch everything is outdated except the CI stuff.

**Comment by EwoutH** [comment]
I'm going to do a bit of weekend, I will take a looks at the CI tomorrow or Monday again.

(@jackiekazil or @tpike3 I would greatly appreciate if I have the permissions by then)

**Comment by quaquel** [comment]
I see a major performance difference between this branch and master (factor 5 or so). I want to dig in and see which commit explains this difference. Will keep you posted.

**Comment by EwoutH** [comment]
In runtime? Quite sure it’s this one https://github.com/projectmesa/mesa/pull/1978/commits/bc613451b2b6668a04c1db9702ec779d4ca43c35, for this branch I set the replications to 1 to iterate faster.

**Comment by jackiekazil** [comment]
Should this one be closed in lieu of the other PR?

**Comment by EwoutH** [comment]
Closing this, #1979 and #1983 have replaced this PR.

**Pull request closed without merging**
