### PR TITLE
Update cookiecutter to flat import style.

### PR DESCRIPTION
**Pull request by jackiekazil**
Description: This updates the cookiecutter template to use the flat style. 

How to test: 
* `mesa startproject` -- Use this to create a new project. 
* `mesa runserver` -- Make sure everything is running correctly. 
* Run black on the newly created project to insure nothing is in violation.

### CODE REVIEW

**Comment by rht** [comment]
The RTD build showed up!

**Comment by rht** [comment]
Waiting for confirmation from @EwoutH.

**Comment by EwoutH** [comment]
Yes, Read the Docs works as intended!

**Comment by rht** [comment]
LGTM

**Pull request merged**
