### PR TITLE
Create __init__.py

### PR DESCRIPTION
**Pull request by YasinEnigma**
create __init__.py to solve #756 issue.

### CODE REVIEW

**Comment by rht** [comment]
LGTM

Also look out if other examples have missing `__init__.py`, to solve the issue once for all.

**Comment by rht** [comment]
Actually, a lot of the examples don't have `__init__.py`, so I think another solution other than `__init__.py` should be used.

**Comment by rht** [comment]
@YasinEnigma I was able to run `shape_example` after adding `server.launch()`. Is the `__init__.py` fix really necessary?

**Comment by YasinEnigma** [comment]
> @YasinEnigma I was able to run `shape_example`'s `run.py` after adding `server.launch()` fix. Is the `__init__.py` fix really necessary?



No, it's not. I tried again, you are right. only adding `server.launch()` solve the problem.

**Comment by rht** [comment]
@YasinEnigma you closed the wrong PR.

**Pull request closed without merging**
