### PR TITLE
ci: Move codespell to pre-commit

### PR DESCRIPTION
**Pull request by rht**
Motivation: using pre-commit is faster than GH Actions.

### CODE REVIEW

**Comment by rht** [comment]
Ready for review + merged. This PR should be squashed+merged.

**Comment by rht** [comment]
I have confirmed that the pre-commit CI works, because I saw the commit
> [Intentionally introduce typos](https://github.com/projectmesa/mesa/pull/2040/commits/bc0a21985ec91a10a13ecc7364be913bd4127114)

failed, with the "allows" and "users" typo fix suggestions.

**Comment by quaquel** [comment]
Looks good to me and good to know you have already tested it.

**Review by EwoutH — APPROVED** [review]
Nice reduction of complexity!

**Pull request merged**
