### PR TITLE
Add NOTICE and full copy of Apache 2.0 license text

### PR DESCRIPTION
**Pull request by rht**
Supersedes #2312.

### CODE REVIEW

**Comment by jackiekazil** [comment]
RE: This ticket and #2312 -- Why are we doing this? What are we trying to fix?

**Comment by rht** [comment]
This is how it is done according to https://www.apache.org/foundation/license-faq.html#Apply-My-Software
> Include a copy of the Apache License, typically in a file called LICENSE, in your work, and consider also including a NOTICE file.

> It is also valuable to tag each of your source-code files in case they become detached from the LICENSE file. To apply the Apache License to your source-code files, one approach is to attach the following notice to as a comment at the top of each file. Replace the copyright templates with your own identifying information:

**Comment by EwoutH** [comment]
My initial intention was to adopt the "standard" way GitHub suggests it.

Changes nothing to the license, but makes it more visible for external projects and in the GitHub interface.

Currently:
image
After this PR:
image

**Comment by Corvince** [comment]
If we use the Apache license we should do it how they suggest -> approved

**Review by Corvince — APPROVED** [review]

**Comment by rht** [comment]
@jackiekazil can I merge the PR or do you have more reservations?

**Comment by jackiekazil** [comment]
Thank you for checking! I am good. Please merge

**Comment by EwoutH** [comment]
Awsome! GitHub seems to like it:

IMG_1477

**Pull request merged**
