### PR TITLE
Replace two loops with dictionary comprehension, list- with generator comprehension 

### PR DESCRIPTION
**Pull request by EwoutH**
Two small changes:

- Replace two loops with dictionary comprehension in batchrunner
- Replace a list comprehension with generator comprehension in datacollection

Both are more concise, readable and improve performance.

### CODE REVIEW

**Comment by rht** [comment]
LGTM

**Comment by rht** [comment]
Pending a rebase based on the line length PR.

**Comment by rht** [comment]
Bump.

**Comment by EwoutH** [comment]
@rht Sorry for the late response, I rebased and reformatted the PR.

**Comment by rht** [comment]
OK

**Pull request merged**
