### PR TITLE
Improve readability of badges

### PR DESCRIPTION
**Pull request by rht**
Can be viewed at https://github.com/rht/mesa/blob/readme/README.md. Based on the README.md of https://github.com/pypa/hatch.

### CODE REVIEW

**Comment by quaquel** [comment]
Looks good to me.

**Review by EwoutH — APPROVED** [review]
Looks good!

Noticed the Python version badge only displays 3.9 and 3.10, probably needs updating in the pyproject.toml.

**Comment by EwoutH** [comment]
Can we disable those required CI runs? They don't work because those jobs don't run on documentation changes.

**Comment by Corvince** [comment]
> Can we disable those required CI runs? They don't work because those jobs don't run on documentation changes.

Yes that would be good, this has happened several times already. But this requires an admin to make the change, I think that's currently @jackiekazil or @tpike3

**Comment by EwoutH** [comment]
Another item for:
- https://github.com/projectmesa/mesa/discussions/1962

**Comment by tpike3** [comment]
> Another item for:
> 
> * [Increase bus factor to at least 3 among all Mesa components #1962](https://github.com/projectmesa/mesa/discussions/1962)

Fair point, I will raise the issue

**Pull request merged**
