### PR TITLE
frontend: Add experimental VegaGrid

### PR DESCRIPTION
**Pull request by Corvince**
Added an experimental VegaGrid via vega-altair. Here is a quick screencast of whats possible with this:

[screen-capture (3).webm](https://github.com/projectmesa/mesa/assets/13568919/efd86066-22ad-431a-8b97-862f0b43a75b)

So, we have the following unique features

- Tooltip for agent data - defaults to all JSON serializable agent data
- declaratively describe chart features instead of imperative portrayal functions
- Interactivity via click-handlers! 

The last one is made possible by vega-altair allowing to define an on_click handler. I than only had to wrap the click handler by first finding the corresponding agent by its unique_id and after any interactions updating the data values.

This means the example shown can be achieved with a simple click_handler that acts upon the clicked agent. That is we only have to define 
```python
def click_handler(agent):
    agent.type = 1 - agent.type
```

to achieve interactivity for changing the agent type!

Then we run the example with 

```python
page = JupyterViz(
    Schelling,
    model_params,
    measures=["happy", make_text(get_happy_agents)],
    space_drawer=make_vega_grid("type:N", click_handler=click_handler),
    name="Schelling",
    agent_portrayal=agent_portrayal,
)
page  # noqa
```

In total I would say the current implementation might be a bit rough, but I think a lot can be improved over time, adding more functions and allowing more customizations. This is just a start.

### CODE REVIEW

**Comment by rht** [comment]
> simple, modern look

It's not that much different than Matplotlib's output. I use scatter plot for Matplotlib so that the markers can be replaced with custom pictures.

- Is this faster than the Matplotlib with png instead of svg?
- Does this support scatter plot with custom images, e.g. wolf-sheep?
- It doesn't seem to have network support: https://github.com/altair-viz/altair/issues/340

**Comment by rht** [comment]
That Altair issue pointed to https://github.com/Zsailer/nx_altair, but this package hasn't been maintained for a while.

**Comment by Corvince** [comment]
> > simple, modern look
> 
> It's not that much different than Matplotlib's output. I use scatter plot for Matplotlib so that the markers can be replaced with custom pictures.

Sorry I put that poorly yesterday and updated the original post. This isn't meant as a replacement for matplotlib, so I removed the comparative phrasing.

**Comment by Corvince** [comment]
I don't know if these questions are specifically addressed at me and how they relate to this PR, but here you go


> - Is this faster than the Matplotlib with png instead of svg?

Probably not, haven't fully tested

> - Does this support scatter plot with custom images, e.g. wolf-sheep?

What do you mean by this? This PR? Then no. Altair? Then yes.

**Comment by rht** [comment]
I don't have time to argue with your nitpicking over semantics (such as in https://github.com/projectmesa/mesa/pull/1811#issuecomment-1731267188).

I can see this PR as a successor to the ideas in #631 and https://github.com/Corvince/mesa-viz. So, we are clear that the `VegaGrid` is a complement to the default Matplotlib-based ones, for the use case when user wants interactivity, and that it is possibly faster (but needs benchmark). Given that this is added in a separate file, it doesn't affect default components. I'm fine with merging this soon.

**Comment by Corvince** [comment]
> I can see this PR as a successor to the ideas in #631 and https://github.com/Corvince/mesa-viz. So, we are clear that the `VegaGrid` is a complement to the default Matplotlib-based ones, for the use case when user wants interactivity, and that it is possibly faster (but needs benchmark). Given that this is added in a separate file, it doesn't affect default components. I'm fine with merging this soon.

Thank you for the clarification. Maybe next time you can make such a statement up front, so it is clearer to me what you think in general about a PR. I sincerely didn't know if you think this is mergeable, you don't like it or if either depends on the answers to the questions you raised.

**Comment by Corvince** [comment]
Reason to close this PR https://github.com/projectmesa/mesa/pull/1805#issuecomment-1737933085

**Pull request closed without merging**
