### PR TITLE
Have Agent use self.model instead of passing it around

### PR DESCRIPTION
**Pull request by njvrzm**
I've rebased these changes against the current master, as the pyconsprints branch seems to have been obsoleted. There were a few code changes I missed in the original PR that I've added as well.

I updated all the relevant documentation I could find, as well. The .ipynb files I edited by hand; I inspected them with jupyter and they look correct but I'm not sure how to verify that they're actually code-correct, so review there would be particularly helpful.

All the test pass and all the examples run. Let me know if anything looks amiss and I can investigate.

### CODE REVIEW

**Comment by njvrzm** [comment]
Just noticed the linter errors; fixing.

**Comment by jackiekazil** [comment]
@njvrzm -- I am afraid the last PR may have caused conflicts. It was a pep8 clean up of examples. Can you review that as well?

@jeetu7 do you have any bandwidth to review this PR? :-)  (If not no worries, I will put it on my todo.)

**Comment by jackiekazil** [comment]
after this PR gets in, I am going to do a release.

**Comment by njvrzm** [comment]
Can do! Looks pretty straightforward.

**Comment by njvrzm** [comment]
All set!

**Comment by jeetu7** [comment]
@jackiekazil 
1) Did visual inspection of the diff. LGTM.
2) I am not able to understand the absence/deletion of __init__ method in test_time.py. If that's alright, it seems good to merge.

**Comment by jeetu7** [comment]
@njvrzm @jackiekazil  Looks like a "self" is missed in the argument at basic/model.py line 38

https://github.com/projectmesa/mesa/pull/297/files#diff-ec1cff5b93589e816da9fbefd6360feeR38

**Comment by njvrzm** [comment]
No, that missing argument is definitely a mistake! I've fixed it, thanks.
As for test_time.py, the MockAgent class's `__init__` wasn't doing anything beyond what the super's does, so it didn't need to be overridden.

**Comment by jackiekazil** [comment]
@jeetu7 Thank you for the review!
@njvrzm Thank you for the PR!!!

High five

**Comment by jackiekazil** [comment]
@njvrzm was there an issue for this?

**Comment by njvrzm** [comment]
I don't believe so!

**Pull request merged**
