### PR TITLE
User parameter saving/loading

### PR DESCRIPTION
**Pull request by TaylorMutch**
This PR works towards adding the ability for a user to capture and load user-settable model parameters. This works by adding an interface in the UI for saving the user-settable model parameters to a locally stored JSON file, which can then be imported via the UI to reset the model using the previously captured model parameters.

Remaining TODOs:

* ~~Add choice loading~~ Done
* ~~Add number input loading~~ Done

### CODE REVIEW

**Comment by TaylorMutch** [comment]
Screenshots illustrating changes:
* Added 'Options' dropdown to right of playback controls
image

* Save modal
image

* Load modal
image

**Comment by rht** [comment]
This hasn't been present in NetLogo. It was still in discussion as of today's timestamp (https://github.com/NetLogo/NetLogo/issues/1162). It will speed up the REPL loop to search for the space of params in some experiments. But again this param search process (either to find the optimum param coordinates or stylized facts to summarize the landscape) could be automated as well.

**Comment by TaylorMutch** [comment]
Simplified the UI for parameter loading
image

**Comment by jackiekazil** [comment]
@TaylorMutch -- can you add this functionality to an example in the examples folder? (It looks like you have screenshots of it, but I don't see any sample models that demo it.)

**Comment by TaylorMutch** [comment]
@jackiekazil These changes are only in the browser code, which means that all of the parameters that are editable in the browser can be saved and reloaded! I can add some documentation under the *Advanced Tutorial* section with a small blurb on saving/loading `UserSettableParameter`s.

**Comment by TaylorMutch** [comment]
Also threw in a rebase - twas getting a bit stale.

**Comment by TaylorMutch** [comment]
@jackiekazil not quite sure why the build took forever, I think that was a Github issue. Regardless, I updated the docs with screenshots. Could you review them?

**Comment by rht** [comment]
I think the end-2-end viz text needs to be disabled for now.

**Comment by TaylorMutch** [comment]
@rht which text are you referring to?

**Comment by TaylorMutch** [comment]
@rht Ah, okay cool. Yes, I have no idea why that took forever to run... though that seems unrelated to the changes made in this PR.

Though, if it was related, I'd be very curious as to why it were so.

**Comment by TaylorMutch** [comment]
As @jackiekazil, @Corvince and I discussed, we might want to hold off on this feature or handle it differently than how it is implemented here. The issue that requires further discussion is what happens to a save file when the underlying model changes.

**Comment by TaylorMutch** [comment]
@rht Any thoughts on save file migrations and how those might be handled?

**Comment by jackiekazil** [comment]
Discussion during today's dev meeting -- 
- Let's not over architect at the moment. Let's just add a failure notice to make sure that users know that it failed when it is not synced and we will build additional migration features in the future.

**Comment by dmasad** [comment]
When loading user parameters in the front-end, the values themselves are being loaded, but the sliders aren't being changed appropriately. The console is showing the error message `cannot call methods on bootstrapSlider prior to initialization; attempted to call 'setValue'`

**Comment by dmasad** [comment]
This is almost implemented. The only remaining issue is a bug where, when the parameters are loaded, the parameter GUI elements don't update to reflect the new values. Anyone should feel free to jump in and fix it.

**Comment by Corvince** [comment]
Just went through the open PRs. I think this will be *very* easy to implement with #700, as the state of the parameters is already saved within the AppStore. So I would only have to steal the file handling and documentation bits from this PR (if @TaylorMutch doesn't object)

**Comment by Corvince** [comment]
Success! This is the complete, naive code based on #700 (without any checks or what-so-ever, but already auto-updating the GUI elements). 
I just had to give it a try. 

```javascript
const SaveLoadParameter = {
  store: parent(AppStore),
  parameter: ({ store }) => store.parameter,
  render: ({ file, parameter }) => html`
    <wl-button onclick="this.nextElementSibling.show()">
      Save or Load
    </wl-button>
    <wl-dialog fixed backdrop id="about-modal">
      <h3 slot="header">Save or Load parameter</h3>
      <div slot="content">
        <wl-textfield type="file"/></wl-textfield>
      </div>
      <div slot="footer" style="justify-content: space-between">
        <wl-button onclick=${loadParameter}>Load</wl-button>
        <wl-button onclick=${saveParameter}>Save</wl-button>
      </div>
    </wl-dialog>
  `
}

function loadParameter({ shadowRoot, store }) {
  let reader = new FileReader()
  reader.onload = ev => {
    store.parameter = JSON.parse(ev.target.result)
  }
  reader.readAsText(shadowRoot.querySelector("input").files[0])
}

function saveParameter({ parameter }) {
  let dataStr =
    "data:text/json;charset=utf-8," +
    encodeURIComponent(JSON.stringify(parameter))
  let downloadAnchorNode = document.createElement("a")
  downloadAnchorNode.setAttribute("href", dataStr)
  downloadAnchorNode.setAttribute("download", "parameter.json")
  document.body.appendChild(downloadAnchorNode)
  downloadAnchorNode.click()
  downloadAnchorNode.remove()
}
```

chrome-capture (3)

**Comment by jackiekazil** [comment]
@Corvince, if my understanding is correct, #700 would supercede? I am comfortable closing this one and proceeding #700. (I will let you do it as confirmation.)

**Comment by SebastianoF** [comment]
Hello there! 
Any follow up on this PR? Looking forward for the new front-end to be landed on master!

**Comment by jackiekazil** [comment]
@SebastianoF -- we struggled with finding Front-end folks. I want to clear out some of these PRs.I know that you commented awhile ago. I would love for you too take this and run with if the offer still stands.

**Pull request closed without merging**
