### PR TITLE
refactor: Change var to const/let for remaining js files

### PR DESCRIPTION
**Pull request by trickroll**
Update remaining files for #1232:
-  BarChartModule.js
-  ChartModule.js
-  NetworkModule_d3.js
-  runcontrol.js

### CODE REVIEW

**Comment by rht** [comment]
Yeah, I saw the merge commits in #1264.
If you want to automatically rebase your branch on top of Mesa's main, you need to add this in your repo's .git/config
```
[pull]
    rebase = true
```
and then do `git pull upstream main`, assuming that "upstream" is defined in .git/config as
```

```
[remote "upstream"]
	url = git://github.com/projectmesa/mesa.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
```

**Comment by rht** [comment]
Another note: it should be possible to automate this conversion process. I just remembered of https://github.com/facebook/jscodeshift, but I can't find a refactoring code that does this yet. It can be used for any automatic refactoring in general.

**Comment by rht** [comment]
LGTM

**Comment by trickroll** [comment]
Thank you for the advice on .git/configs. Super appreciative as I work through the git nuances. :)

**Pull request merged**
