### PR TITLE
[docs improvement] Add snippet about using `numpy`'s random

### PR DESCRIPTION
**Pull request by majdal**
As described in #958

### CODE REVIEW

**Comment by Corvince** [comment]
Thanks for the PR @majdal! But be careful, you are "just" setting an additional random module for the agent, so you will have `agent.random` and `model.random` and if you want reproducible runs you have to set both seeds. I think a saner approach would be to override `model.random` with with the numpy module.

**Comment by jackiekazil** [comment]
@majdal also, can you submit the PR to the docs branch, so we can do a test build there? 
_Sorry, we should probably document that in our contributor guide._

**Comment by majdal** [comment]
@Corvince Actually, I was thinking about this when I used numpy's random in my own model. I was checking [this line](https://github.com/projectmesa/mesa/blob/master/mesa/agent.py#L29), and it seems like `agent.random` is just `agent.model.random`, and since we're setting the `model.random`, we wouldn't need to modify the model class directly, no?

@jackiekazil I'll do that now! And yes, including this in the contributor guide would be super useful.

**Comment by Corvince** [comment]
> @Corvince Actually, I was thinking about this when I used numpy's random in my own model. I was checking [this line](https://github.com/projectmesa/mesa/blob/master/mesa/agent.py#L29), and it seems like `agent.random` is just `agent.model.random`, and since we're setting the `model.random`, we wouldn't need to modify the model class directly, no?
> 

Yes you are technically correct! And while this is the best kind of correct, I think it is also super confusing and counterintuitive. I still would prefer to modify `model.random` directly :)

**Comment by rht** [comment]
I cherry-picked the last commit of this PR in #1204. I will do the further improvement in that PR.

**Pull request closed without merging**
