### PR TITLE
Travis: Add pypy3

### PR DESCRIPTION
**Pull request by rht**
This addresses #882.

### CODE REVIEW

**Comment by rht** [comment]
I'm not sure why there is no Travis running here ...

**Comment by Corvince** [comment]
> I'm not sure why there is no Travis running here ...

No idea why it doesn't show up. It did run though, but failed at installing pandas (https://travis-ci.org/github/projectmesa/mesa/jobs/718907972)

**Comment by rht** [comment]
It looks like it fails at pandas' dependency, ujson. I will keep this PR open and retry on future version of PyPy. Though PyPy developers claimed that pandas has been supported since pypy5.9 (https://doc.pypy.org/en/latest/release-v5.9.0.html#pypy2-7-and-pypy3-5-v5-9-dual-release). The current Travis PyPy is 7.1.1.

**Comment by Corvince** [comment]
Your link only mentions pypy2.7, but from what I could infer from googling around, yes, it should work with pandas. Maybe just an issue with travis? @rht could you (or someone else) try it locally?

**Comment by rht** [comment]
Tested on my laptop. 
pypy3-7.3.1:
```
97 passed, 1 warning in 11.26s ================================================
```

With normal python 3.8
```
97 passed, 2 warnings in 11.63s ===============================================
```

**Comment by rht** [comment]
I probably need a simulation with a huge grid size in order to highly PyPy's speedup.

**Comment by rht** [comment]
I ran the comparison on the `bank_reserves` example, , because it doesn't have the web GUI.
The speedup is significant!
PyPy3-7.3.1
```
python batch_run.py  89.72s user 2.78s system 100% cpu 1:31.72 total
```
CPython 3.8
```
python batch_run.py  173.73s user 2.19s system 100% cpu 2:55.10 total
```
A 1.9x speedup!

**Comment by rht** [comment]
Here I removed 3.5 to make room for PyPy3. This is also justified by the fact that 3.5's EOL 2020-09-13.

**Pull request closed without merging**
