### PR TITLE
style: prettify js files

### PR DESCRIPTION
**Pull request by akrabdev**
This  is addressing #1258. By running Prettier formatter on js files in `mesa/visualization/templates/..` I ignored `*.min.js` files as well.

I used the default prettier configuration which was also used in #1225 

I recommend adding prettier config file `.prettierrc` and `.prettierignore`  in the future.

### CODE REVIEW

**Comment by rht** [comment]
Thank you for using conventional commit message (https://www.conventionalcommits.org/en/v1.0.0/). It's not enforced in this repo, but always good. Sorry for the merge conflict, this is because of #1265, which is done manually.

Note that bootstrap-switch is an external dependency.

We are doing standard Prettier, so .prettierrc is not needed for now. But adding .prettierignore (in a separate PR) is a good idea. The external dependencies will soon be moved to a separate folder that can then be ignored.

**Comment by akrabdev** [comment]
I reverted changes to boostrap-switch.js and resolved the conflicts

**Comment by rht** [comment]
@akrabdev it would be great to squash the commits into 1 commit, because logically they are within the same theme. It is fine to have multiple commits in a PR as long as each commit does logically different change. This is the convention used in projectmesa/mesa.

**Comment by rht** [comment]
First, you should rebase your branch on top of projectmesa/mesa's main: `git pull --rebase upstream main`, assuming you have already defined upstream as a remote in your .git/config.

**Comment by akrabdev** [comment]
Commits squashed!, thank you for the heads up

**Comment by rht** [comment]
@akrabdev you haven't removed the bootstrap-switch.js in your latest commit. Also, you haven't added NetworkModule_d3.js

**Comment by akrabdev** [comment]
@rht cleaned up the mess. `NetwrokModule_d3.js` already formatted as in #1225

**Comment by rht** [comment]
I forgot that I did the NetworkModule_d3.js one.

**Comment by rht** [comment]
LGTM

**Comment by akrabdev** [comment]
Thank you too for the detailed instructions! @rht 

when the state of js files  is ready to add `.prettierignore` , I can work on it.
 
Also we can look into [pre-commit hook](https://prettier.io/docs/en/precommit.html) tool to ensure committed .js files are  formatted.

**Comment by rht** [comment]
Sounds good.

> Also we can look into [pre-commit hook](https://prettier.io/docs/en/precommit.html) tool to ensure committed .js files are formatted.

Currently, there is no `npm` config being set up in the development environment of Mesa. We haven't decided yet on whether we should do this, because it increases the effort for the setup. For now, the `prettier` can be run in the CI instead.

**Pull request merged**
