### PR TITLE
Add Conway's Game of Life simulation to the examples.

### PR DESCRIPTION
**Pull request by VictorNorman**
Fixes issue #182.

### CODE REVIEW

**Comment by jackiekazil** [comment]
I am going to review this this week.

**Comment by VictorNorman** [comment]
Sounds good.

—
Prof. Victor Norman
Computer Science Dept., Calvin College
vtn2@calvin.edu<mailto:vtn2@calvin.edu> / 616 526-7805<tel:616%20526-7805>


“A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away.” -- Antoine de Saint Exupéry

**Comment by jackiekazil** [comment]
This looks good. We are working on creating standards for what is a model package. **One of the things that all of our model packages need is a README.md. Would you be able to add one with this pull request? **
(Let me know if you are not familiar w/ how to do that and I can help.)

This is what Netlogo includes for there "README": http://ccl.northwestern.edu/netlogo/models/Life
I think we could do... 
```
## What is it
## How to run the model
## HOW TO CITE
(For the model itself:)
```
^^ I think those are the most important. Yes? No?

Feel free to take license in deciding on what is additionally important based on the Netlogo format. I don't think everything is needed in every case. It can also be edited in the future, and lastly, this will help us think through our standards for models in the future.

**Comment by jackiekazil** [comment]
@VictorNorman I am going to merge this, so it is added in, and say that my request will be an artifact of #62. Feel free to submit another PR if you do do this, before someone else gets to it.

**Pull request merged**
