### PR TITLE
Change index at DataFrame creation in get_agent_vars_dataframe

### PR DESCRIPTION
**Pull request by Tortar**
This is slightly faster as one would expect, code to reproduce:

```
import timeit
a = timeit.timeit("s =pd.DataFrame.from_records(t); s = s.set_index(['a', 'b'])","import pandas as pd\nq=list(range(1000)); t={'a':q,'b':q}", number=1000)
b = timeit.timeit("s =pd.DataFrame.from_records(t, index=['a', 'b'])","import pandas as pd\nq=list(range(1000)); t={'a':q,'b':q}", number=1000)
print(a, b)
```

### CODE REVIEW

**Comment by rht** [comment]
> This is slightly faster ...

By how much?

**Comment by Tortar** [comment]
A good 20% :-), expected more, but it seems that indexing costs (a lot) also at creation

**Comment by Tortar** [comment]
Actually it is almost the same with more columns

```
import timeit
a = timeit.timeit("s =pd.DataFrame.from_records(t); s = s.set_index(['a', 'b'])","import pandas as pd\nq=list(range(10000)); t={x:q for x in 'abcdefghilmn'}", number=100)
b = timeit.timeit("s =pd.DataFrame.from_records(t, index=['a', 'b'])","import pandas as pd\nq=list(range(10000)); t={x:q for x in 'abcdefghilmn'}", number=100)
print(a, b)
```

gives me anyway a 15% better where we have 12 columns

```
import timeit

a = timeit.timeit("s =pd.DataFrame.from_records(t); s = s.set_index(['a', 'b'])","import pandas as pd\nq=list(range(10000)); cols = 'abcdefghilmnopqrstuvz123456'; t={x:q for x in cols}", number=100)
b = timeit.timeit("s =pd.DataFrame.from_records(t, index=['a', 'b'])","import pandas as pd\nq=list(range(10000)); cols = 'abcdefghilmnopqrstuvz123456'; t={x:q for x in cols}", number=100)
print(a, b)
```

gives me anyway a 30% better where we have 30+ columns

**Comment by rht** [comment]
LGTM

**Pull request merged**
