### PR TITLE
add test_time back

### PR DESCRIPTION
**Pull request by quaquel**
As evidenced by #2350 and #2359, its rather useful to keep testing this even though it is deprecated.

### CODE REVIEW

**Comment by quaquel** [comment]
I know why the tests are breaking, but I have run out of time now to fix them all. Will pick this up later today.

**Comment by quaquel** [comment]
All unit tests are now fixed. This is ready to be merged

**Review by Corvince — APPROVED** [review]
great, thank you!

**Comment by EwoutH** [comment]
Awesome, thanks!

**Pull request merged**
