### PR TITLE
SolaraViz: Remove card title

### PR DESCRIPTION
**Pull request by rht**
They are soon going to be part of one umbrella of "measures", instead of distinctly named ones. If a user wants to add a title, they can do it inside Matplotlib/Altair.

### CODE REVIEW

**Comment by tpike3** [comment]
@rht Thanks! -- Could you elaborate on "They are soon going to be part of one umbrella of measures". Is this going to be a change to Mesa, Solara or both? 

Could you add to the visualization tutorial adding names to the plots? I think this is a small but critical feature for users.

**Comment by EwoutH** [comment]
How can I help move this forward?

**Comment by rht** [comment]
> Could you elaborate on "They are soon going to be part of one umbrella of measures"

https://github.com/projectmesa/mesa/discussions/2236, and in https://github.com/projectmesa/mesa/pull/2263, where measures and space are merged into "components" (what I earlier called measures).

> Could you add to the visualization tutorial adding names to the plots? I think this is a small but critical feature for users.

Currently there is no public API for that, and this PR doesn't add/remove any feature in this area.

> How can I help move this forward?

This PR just needs a clarification answer to @tpike3 's questions. Unless there is other missing aspect.

**Comment by EwoutH** [comment]
@rht @Corvince what's the current state / trajectory of this PR?

**Comment by quaquel** [comment]
This PR is outdated and in the revised solara_viz this code is not used anymore.

**Pull request closed without merging**
