### PR TITLE
viz: Combine code for rendering in browser and Jupyter

### PR DESCRIPTION
**Pull request by rht**
This unifies the rendering code, simplifying it and reducing maintenance overhead. Solara now has a built-in way to show the sidebar, when the hamburger button is clicked. @tpike3 you might want to update the Mesa-Geo equivalent.
2024-07-14T13:56:19,646024398-04:00

### CODE REVIEW

**Comment by rht** [comment]
Clarification: the screenshot was taken from a Jupyter notebook UI.

**Comment by rht** [comment]
Request for review: @projectmesa/maintainers

**Comment by rht** [comment]
You have to run https://github.com/projectmesa/mesa-examples/tree/main/examples/schelling_experimental (after manually editing `from mesa.experimental import JupyterViz, ...` to `from mesa.visualization import JupyterViz`. But more importantly, to test the UI change when rendered on a Jupyter notebook. There is no .ipynb on that example folder yet, so you have to copy-paste the app.py code to a fresh new notebook.

**Comment by jackiekazil** [comment]
Thank you. I wonder if this is an opportunity to create an example of the solara app in a jupyter notebook? 

Regardless, this LGTM.

**Review by jackiekazil — APPROVED** [review]

**Comment by rht** [comment]
Will do during the revamp of the examples to Mesa 3.0.

**Comment by EwoutH** [comment]
Looks like good stuff, thanks for working on this!

**Comment by EwoutH** [comment]
I would like to resolve this error in the [stable version](https://mesa.readthedocs.io/en/stable/tutorials/visualization_tutorial.html) of our Visualization Tutorial. 

image

Apparently this PR does that for the main mesa branch. Can we cherry pick some part of it (in a non-breaking way) to resolve this warning on Mesa 2.3.x?

**Pull request merged**
