### PR TITLE
Merging the modular server w/ merge fix w/ master 

### PR DESCRIPTION
**Pull request by jackiekazil**
@dmasad -- I see your pull request and raise you a pull request... ;-)
This was my test run at making the clean_modules.79 play nicely w/ master. 
Please review. If this looks good, post to the ticket, then I will update clean_modules.79 in the same way so that is can merge nicely with master when we get there.

Also, we should see how Travis comes back. :wink:

### CODE REVIEW

**Comment by dmasad** [comment]
So is this a PR with the conflicts resolved?

**Comment by jackiekazil** [comment]
Yes. it should be. It is a copy of clean_modules.79 w/ a master rebase + conflicts merged. 
We could move to this pull request it if is nice and works out or I could do it to the other branch.
I am starting to think that moving to this one (if it merged correctly), would be better. 
Have you looked at the files? Does this look correctly merged to you?

**Comment by dmasad** [comment]
It looks good! We should try running the visualizations -- I can try that tomorrow, if you want. But if those run, and the tests pass, I think it's probably all set.

**Comment by jackiekazil** [comment]
@dmasad --- sounds good --- you check the visualizations in this branch, and I will keep poking around at things.

**Comment by jackiekazil** [comment]
@dmasad did you have a chance to check this?

**Comment by dmasad** [comment]
Not yet, sorry!

**Comment by dmasad** [comment]
Okay, reviewed and tested, and it looks good!

**Comment by jackiekazil** [comment]
From everything that I can see. This looks good. I am merging. I will also push an update to Pypi.

**Pull request merged**
