### PR TITLE
Fix links in example README.md

### PR DESCRIPTION
**Pull request by jackiekazil**
Fix broken links.

### CODE REVIEW

**Comment by quaquel** [comment]
This breaks the links on read the docs. See #2448 and #2528. 

I don't know of a way to use the readme when generating the [read the docs examples landing page](https://mesa--2570.org.readthedocs.build/2570/examples.html) and have links work both within github and within readthedocs.

**Comment by EwoutH** [comment]
This issue keeps coming back, so we should try to fix it somehow.

One thing that might work is move the Readme, for example by breaking the Readme into a Basic and Advanced section, so the relative links would be the same for GitHub and RTD.

**Comment by quaquel** [comment]
> This issue keeps coming back, so we should try to fix it somehow.

I agree

> One thing that might work is move the Readme, for example by breaking the Readme into a Basic and Advanced section, so the relative links would be the same for GitHub and RTD.

That is not the problem. The issue is that readthedocs requires `examples/basic/ect`, while github uses `basic/ect`. So, one option is to just splice it the examples part when generating the readthedocs file. This could be done in docs/conf.py and then `setup_examples_pages`.

**Comment by jackiekazil** [comment]
Shall I close this?

**Pull request closed without merging**
