### PR TITLE
sphinx: Use PyData theme

### PR DESCRIPTION
**Pull request by rht**
This is an experiment in changing the doc theme.

### CODE REVIEW

**Comment by rht** [comment]
Rendered at https://mesa--1699.org.readthedocs.build/en/1699/.

**Comment by tpike3** [comment]
I like it! I am good with merging. @jackiekazil  what do you think?

**Review by tpike3 — APPROVED** [review]
Looks awesome! and @jackiekazil  also agreed.

**Comment by wang-boyu** [comment]
Looks like https://mesa.readthedocs.io/en/main is updated but https://mesa.readthedocs.io/en/stable/ isn't.

**Comment by rht** [comment]
I assume stable means the latest release, but not sure.

**Comment by rht** [comment]
It's at commit 9a07a485, which commit message is "Bump version to 1.2.1", so it is the latest release.

**Comment by wang-boyu** [comment]
Oh right, my bad. This is as expected then.

**Pull request merged**
