### PR TITLE
refactor: update var to const/let in InteractionHandler.js

### PR DESCRIPTION
**Pull request by trickroll**
Per #1232, updates InteractionHandler.js to replace `var` with `const`/`let`

### CODE REVIEW

**Comment by rht** [comment]
Thank you! Can you edit the commit message to be more informative? Like https://github.com/projectmesa/mesa/pull/1265/commits/7bf8c693f4ef441cb6caed1558865e022365ead0 but more specifically on InteractionHandler.js.

**Comment by trickroll** [comment]
Updated commit message. Thank you for pointing that out!

**Comment by rht** [comment]
You have updated the PR title, but not the Git commit message.

**Comment by trickroll** [comment]
Sorry for the confusion. Performed a `git commit --amend -m` command

**Comment by rht** [comment]
LGTM

**Pull request merged**
