### PR TITLE
Remove key check in BaseScheduler.agent_buffer

### PR DESCRIPTION
**Pull request by Tortar**
It is not necessary to check the presence of the key

### CODE REVIEW

**Comment by Corvince** [comment]
On mobile so I can't check if I'm thinking correctly, but I think we check again in case an agent was removed in another agents step (e.g. killing)

**Comment by Tortar** [comment]
I thought this was the meaning bit it isn't possible to do so, it would result in an error because .keys cannot be iterated while removing or adding

**Comment by Tortar** [comment]
mmh yes but the problem is that it doesn't change the fact that you can't add agents during stepping anyway

**Comment by Tortar** [comment]
right I think it's my fault :-) seems like we should revert it

**Comment by Tortar** [comment]
I think that apart this bug there are some other bugs related to this inside some more advanced schedulers not checking the condition

**Comment by Tortar** [comment]
I think that a comment stating  why the list transformation is necessary should be added

**Pull request closed without merging**
