### PR TITLE
test: Remove place_agent duplicate warnings

### PR DESCRIPTION
**Pull request by rht**
Because of #2083, some faulty test code have been caught. cc: @puer-robustus

### CODE REVIEW

**Comment by EwoutH** [comment]
Can you split of the ruff update in a separate PR? I like to keep PRs atomic.

**Comment by rht** [comment]
Done.

**Comment by EwoutH** [comment]
Thanks! I guess it isn’t allowed in current Mesa to initialize agents with a `pos` right? I have seen it in other models, maybe we should write that up somewhere.

**Comment by rht** [comment]
> Thanks! I guess it isn’t allowed in current Mesa to initialize agents with a pos right?

Allowed but not recommended.

> Also, which warning is this removing exactly?

#2083

**Review by EwoutH — APPROVED** [review]

**Pull request merged**
