### PR TITLE
Update docs/README.md

### PR DESCRIPTION
**Pull request by jonahaag**
As discussed in #1117, I went back to all `1.`'s in the numbered lists and instead let markdown increment automatically. For this to work properly, whitespaces in front of nested bullet points were replaced by two tabs.

### CODE REVIEW

**Comment by rht** [comment]
In order for your branch commit history to be clean (without merge commits), you should add this in your ~/.gitconfig:
```
[pull]
    rebase = true
```
This way, your branch's commits are re-applied on top of the main branch you pull from, instead of it doing messy merge operations.

**Comment by rht** [comment]
Other than the extra merge commit issue (you can look up from the internet on how to delete the last commit, and then you do `git pull` again), the PR content LGTM.

**Comment by jonahaag** [comment]
True, I am sorry for that. I forgot to do the rebase before and then solved the resulting conflict via merge commit using the GitHub web IDE, which was just me being lazy

**Comment by jonahaag** [comment]
I hope this is fine now, took me a while to figure out how to do this in a clean way. 

Changes remain the same for the most part, I also removed some unnecessary code marks to keep everything consistent

**Comment by rht** [comment]
LGTM. As can be seen in https://github.com/jonahaag/mesa/tree/update-docs-readme/docs.

**Pull request merged**
