### PR TITLE
Update History to reflect release_3.0.0b1 notes

### PR DESCRIPTION
**Pull request by jackiekazil**

### CODE REVIEW

**Comment by EwoutH** [comment]
@jackiekazil Thanks! Could you review #2369 and then re-generate the release notes?

@tpike3 would you like this beta to wait for your update of the tutorial? (latest docs get updated between releases)

**Comment by jackiekazil** [comment]
@EwoutH - done.  I can update the date and release tomorrow if that works for you.

**Comment by EwoutH** [comment]
Awesome! #2381 should be included, and then we can release.

I think the significant part of the highlights should be about the examples now being in Mesa itself, being directly importable and being included in the docs.

**Review by EwoutH — APPROVED** [review]
I’m going to pre-approve this PR, so you can merge without any hassle when it’s ready.

If you get stuck in any part of the process, just say where you left it and I can finish it tomorrow morning. Otherwise I look forward to waking up to a new pre-release! :)

**Comment by jackiekazil** [comment]
@EwoutH, this is complete. I think I got everything, but I would love a second review to make sure I didn't miss anything.

**Pull request merged**
