### PR TITLE
Added directed edges functionality to D3 Visualization

### PR DESCRIPTION
**Pull request by rozenlicht**
Added DirectedGraph example (VirusOnNetworkDirected). 
Appended arrowhead SVG to D3.js module.
(partially) fixes issue #667

### CODE REVIEW

**Comment by AdamCordner641** [comment]
Hi. I am currently working on a mesa-based project and it would be great if I could use this directed edge functionality in my project.  I'm aware this PR is almost 2 years old, but is there any chance of this change being merged to the main mesa branch?

**Comment by rozenlicht** [comment]
FYI I'm not actively using MESA anymore, so can't really help with updating the branch to master without diving in again, but of course nice if someone that likes to use this gets this merged! :-)

**Comment by AdamCordner641** [comment]
No problem, thanks for responding and letting me know :)

**Comment by AdamCordner641** [comment]
Hi @rht. I have noticed you merge a lot of PRs to the main mesa branch. If possible, would you be able to merge this PR? Sorry if you're the wrong person to ask about this, I'm not sure who in this project has write access.

**Comment by tpike3** [comment]
> Hi @rht. I have noticed you merge a lot of PRs to the main mesa branch. If possible, would you be able to merge this PR? Sorry if you're the wrong person to ask about this, I'm not sure who in this project has write access.

@AdamCordner641 Due to the age of this pull request I would ask that you resubmit the PR. As the dev team is more active now we will get to it directly.

**Comment by rht** [comment]
Superseded by #1223

**Pull request closed without merging**
