### PR TITLE
Include examples in readthedocs (port)

### LINKED ISSUE #2360: Experimental documentation
The documentation for Cell Space and DEVS in Experimental is duplicated. 

[page](https://mesa.readthedocs.io/stable/apis/experimental.html#experimental.__init__.Slider) 

Example of priority being duplicated. 
image

Happy to help if needs be!

### PR DESCRIPTION
**Pull request by EwoutH**
_This is a manual port of #2382 because some weird shit happened there after merging the main branch a few times into it. This is a clean version based of that PR._

This updates conf.py to create markdown files for including the examples in the documentation. It also cleans up some warning on RTD, which happened while debugging the code. In this process, this also fixes #2360.

It currently only covers the basic examples because the advanced examples are not fully cleaned yet.

### CODE REVIEW

**Comment by quaquel** [comment]
this breaks on RTD because some files have not been renamed properly (my hunch).

**Comment by EwoutH** [comment]
Thanks, indeed forgot to rename the README.md files. It now [passes](https://mesa--2392.org.readthedocs.build/2392/examples.html).

**Comment by quaquel** [comment]
This fixes the build. I'll review later this morning.

**Comment by quaquel** [comment]
Looking at the diff, it seems good to go. This one has 2 more files that are changed (i.e.., removed). Not sure how this PR is any different from the original once its squashed and merged.

**Review by quaquel — APPROVED** [review]

**Comment by EwoutH** [comment]
Thanks!

> Not sure how this PR is any different from the original once its squashed and merged.

It prevents the 3 duplicate files from being included. Maybe that would have resolved itself when squashing, or maybe not.

**Pull request merged**
