### PR TITLE
The big backport: Bring many Mesa 3.0 features to 2.4.0

### PR DESCRIPTION
**Pull request by EwoutH**
A big backport which brings many Mesa 3.0 features to Mesa 2.4.0 in a backward-compatible way.

New deprecation warnings are included, but no breaking changes.

The HISTORY.md contain new release notes (please review) and a draft release is [available here](https://github.com/projectmesa/mesa/releases/tag/untagged-56ce2c0247231bbd07e8).

### CODE REVIEW

**Comment by EwoutH** [comment]
All 2.x example models pass without errors and remarkably few warnings.

**Comment by Corvince** [comment]
Awesome PR! Crazy that most of the things "just work". I think architectural mesa is much better these days and this starts to show.

**Comment by EwoutH** [comment]
Thanks!

> Crazy that most of the things "just work". I think architectural mesa is much better these days and this starts to show.

Yes, fully agree. It's amazing to be able to do a backport with over a dozen functional PRs and not have a single example fail.

To be fair, most of this is AgentSet. I didn't touch the time internals and such.

**Comment by jackiekazil** [comment]
This is really amazing!

**Pull request merged**
