### PR TITLE
Make HexGrid private and create HexSingleGrid and HexMultiGrid

### PR DESCRIPTION
**Pull request by Tortar**
Made HexGrid private and created two new grid classes as discussed in the dev meeting. This is a breaking change to defer until 2.0.

### CODE REVIEW

**Comment by jeremander** [comment]
To ease backward compatibility, can you keep `HexGrid` and deprecate it?  For example, have `HexGrid` subclass `HexSingleGrid` and issue a `DeprecationWarning` upon construction?

**Comment by Tortar** [comment]
This seems like a good idea :+1:

**Comment by Tortar** [comment]
But I have not much time to work on this now, also it should be done with care I think since if we issue it in `__init__` we will overwrite the `__init__` method in the superclass so this should be managed somehow

**Comment by Tortar** [comment]
Actually did it

**Comment by Tortar** [comment]
I don't see any merge conflict @rht , however I resolved one sometime ago

**Comment by rht** [comment]
I have rebased the branch. RTD build has a failure that is unrelated to this PR
```
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168
```

@EwoutH any idea about the situation?

**Comment by rht** [comment]
Merged, thank you!

**Pull request merged**
