### PR TITLE
Make the internal grid and empties_built in Grid class private

### PR DESCRIPTION
**Pull request by Tortar**
The internal grid in the Grid class should be made private as was done in #815, the internal mechanic of the class should not be used by the user (if he doesn't really want to do so) and we should be free to change it as we want if needed.

Something should be changed in the tests folder also, but I'd like to finish the PR when it gets some approval :-)

### CODE REVIEW

**Comment by rht** [comment]
Yeah, I agree with this proposal.

And in general, it is indeed more effective if you sketch a draft PR and wait for agreement, so that your effort is not wasted.

**Comment by Tortar** [comment]
will do that more often!

**Comment by Tortar** [comment]
Everything should be done now, I realized that also `empties_built` shouldn't be public so I put all together in this PR, hope this is welcomed!

**Comment by rht** [comment]
`Grid.grid` has been a public attribute, but it has never been endorsed in the docs, so I think it's fine to make it private without having to wait to do the change in Mesa 2.0.

**Pull request merged**
