### PR TITLE
Color Patches Model example

### PR DESCRIPTION
**Pull request by ReblochonMasque**
Wrote an example model.
Faced some API glitches:
* several row/col col/row issues as mentioned elsewhere.
* direct attributes access forcing a number of specific choice of attribute names
* canvas parameters (lines separating the cells on the canvas)

I documented these in the code in preparation to addressing the issues; however, I am unsure if this example should be published as-is, or if the comments added are a no go. (it probably depends on the timeline to correct the API)
With current settings of the example, the lines separating cells on canvas are only visible on half of it.

Request a pull for a **quick eyeball** on the code and **advice** on how to proceed.
This is not a WIP, it can be merged if the comments added and the canvas glitch are okay.

### CODE REVIEW

**Comment by jackiekazil** [comment]
@ReblochonMasque 
1. Waiting to merge until we have a convo about x,y issue -- I think this has come up before, but I don't remember the result. 
2. Why is the grid outline only spanning 1/2 the visualization? Is that an artifact of Mesa OR is that on purpose? (I am thinking Mesa, and maybe that is a bug to fix?)

**Comment by ReblochonMasque** [comment]
The grid canvas drawing of the white lines that separate the cells has a problem for rectangular grids  issue #191. This problem is hidden for square grids which is most of the other examples.

**Comment by jackiekazil** [comment]
No keep it as is. So we can make sure it is fixed. 
So, when #191 is fixed, then this model would be displaying properly?

**Comment by ReblochonMasque** [comment]
Yes, when #191 is fixed, the display of rectangular grids will be good

**Comment by jackiekazil** [comment]
That is what I thought, but I wanted to confirm. This all looks good then. Merging.

**Pull request merged**
