### PR TITLE
mypy: Improve annotations

### PR DESCRIPTION
**Pull request by rht**
This is a subset of #835 to make it easier to review and merge.

### CODE REVIEW

**Comment by rht** [comment]
I'm deleting Python 3.6 from CI because its numpy version is too old, which doesn't have the Mypy stubs.

**Comment by rht** [comment]
For [perf: ContinuousSpace: Use math instead of np for get_distance](https://github.com/projectmesa/mesa/pull/1212/commits/847693fcc3fea60601d41234329614c1c37a8f37), it's a well known issue that `numpy` functions are much slower than `math` functions for scalar arguments.

**Review by tpike3 — CHANGES_REQUESTED** [review]
- Well it took me awhile, but I am learning a lot researching your improvements
- Can you squash your commits, although in this pull request it seems three things are really happening (remove, 3.6, improve annotations, improve dist calc). 
- Other than that LGTM

**Comment by rht** [comment]
If I squash the commits, it will be hard to tell what that 1 commit actually does. Too many things happening in 1 commit.

**Comment by rht** [comment]
I'm fine with multiple commits in 1 PR as long as each commit does different things logically, and the commits are not messy.
See also https://news.ycombinator.com/item?id=11407485.

**Comment by rht** [comment]
The reason why I did the `np` -> `math` in this PR is that it is a side effect of not relying on `numpy` for typing. But later on I figured out that my `mypy` setup uses an outdated `numpy` where it didn't have stubs yet.

**Comment by tpike3** [comment]
> If I squash the commits, it will be hard to tell what that 1 commit actually does. Too many things happening in 1 commit.

I agree with this and am okay with multiple commits. However, to make sure we are synced as I look at this as cementing our processes. When we would say to do multiple pull requests vs multiple commits? Per the ycombinator discussion there is no easy answer but how would you describe the "rule of thumb" we should use?

**Comment by rht** [comment]
When this PR is merged, each of the commits will contain a link to this PR on GitHub. I'd say it is fine to have multiple commits in 1 PR as long as they are within the same theme.

**Comment by tpike3** [comment]
> When this PR is merged, each of the commits will contain a link to this PR on GitHub. I'd say it is fine to have multiple commits in 1 PR as long as they are within the same theme.

Works for me.

**Pull request merged**
