### PR TITLE
Update to version 1.1.0

### LINKED ISSUE #1436: v1.1.0 Safford Release
Milestone: https://github.com/projectmesa/mesa/milestone/31

Highlighted changes:
- #1376 > 6x perf speedup for add/remove agent in `ContinuousSpace`
- #1391 correctness fix for `SimultaneousActivation` and `StagedActivation`
- #1399 make `self.running = True` optional. We need to tell existing users that initializing this is no longer necessary, and so, reducing the boilerplate code
- #1435 Allow user-specified local dir to be served by Tornado. Needed by Mesa-Geo
- #1413 Allow batch_run to take arbitrary parameters

### PR DESCRIPTION
**Pull request by rht**
Fix #1436.

### CODE REVIEW

**Comment by jackiekazil** [comment]
I will do a review this evening.

**Comment by jackiekazil** [comment]
@rht  -- is there anything else to add?

**Comment by rht** [comment]
I don't think so. I have added the most recent newly merged PR. Let me update the date to Oct 6.

**Comment by rht** [comment]
I have bumped the date to Oct 8th just in case.

**Comment by jackiekazil** [comment]
Should any of these be included? 
https://github.com/projectmesa/mesa/pulls?q=is%3Amerged+is%3Apr+no%3Amilestone+

**Comment by rht** [comment]
They all happened before 1.0.0 release, so, they should have been included in 1.0.0 changelog. We can do this in a separate PR.

**Comment by rht** [comment]
Heads up, #1440 was just merged, and has been included in the changelog here. This PR has been rebased accordingly. I have also changed the date to 10-10. The previous release date was 07-06, and so we missed an opportunity to make the day and the month match.

I hope we can merge this PR on Oct 10th. Don't miss the chance.

**Comment by jackiekazil** [comment]
LGTM

**Pull request merged**
