### PR TITLE
Added optional title feature to ChartModule

### PR DESCRIPTION
**Pull request by anjalinair012**
A suggested solution to issue #954

### CODE REVIEW

**Comment by jackiekazil** [comment]
This looks good. Can you add an example implementation into one of the examples?

**Comment by anjalinair012** [comment]
Example \mesa\examples\charts\charts\server.py has been modified for testing. Please refer to mesa\docs\issue_954.rst .

**Comment by JaslinRikkaz123** [comment]
I have tried this but it doesn't show the title in the chart module output. What i have to do to get the chart title?

**Comment by catherinedevlin** [comment]
I tried producing an updated PR with this code - https://github.com/projectmesa/mesa/pull/1666 - but like @JaslinRikkaz123, did not see the title actually showing up on the screen.  I also think that, if it is made to work, it should work with all the visualizations (bar, pie, ...), not just line.

**Comment by Corvince** [comment]
Thank you for the PR and sorry for never putting it forward 

If this is still actively followed please re-open the PR at https://github.com/projectmesa/mesa-viz-tornado
But note that we are moving towards a new pure python frontend

**Pull request closed without merging**
