### PR TITLE
Remove visualization modules from `mesa.experimental`

### PR DESCRIPTION
**Pull request by quaquel**
This removes visualization modules from `mesa.experimental`.

### CODE REVIEW

**Comment by EwoutH** [comment]
Had already a draft branch, thanks! Will review after diner.

**Comment by EwoutH** [comment]
The whole [components](https://github.com/projectmesa/mesa/tree/main/mesa/experimental/components) folder can also be removed, right?

**Comment by quaquel** [comment]
> The whole [components](https://github.com/projectmesa/mesa/tree/main/mesa/experimental/components) folder can also be removed, right?

good point, I removed those as well.

**Review by EwoutH — APPROVED** [review]
Thanks!

**Pull request merged**
