### PR TITLE
Docker: Update to use Solara viz

### PR DESCRIPTION
**Pull request by rht**
Not yet tested. Note that the current Docker setup is broken because the examples folder is now gone (moved to mesa-examples repo).

### CODE REVIEW

**Comment by tpike3** [comment]
> Not yet tested. Note that the current Docker setup is broken because the examples folder is now gone (moved to mesa-examples repo).

You are absolutely correct, thanks for catching this!

**Comment by rht** [comment]
@tpike3 this is ready to merge. I have tested locally.

**Comment by rht** [comment]
@tpike3 ?

**Comment by rht** [comment]
@tpike3 ?

**Comment by tpike3** [comment]
Sorry for the delay so how I missed this one

**Pull request merged**
