### PR TITLE
fix: Use model.schedule.steps -> mode._steps for batch_run

### PR DESCRIPTION
**Pull request by rht**
Addresses https://github.com/projectmesa/mesa-examples/issues/126

### CODE REVIEW

**Review by EwoutH — APPROVED** [review]
Looks good, thanks!

Should we add a test case for this somewhere? Or add an example model to the CI that uses this?

**Comment by EwoutH** [comment]
@dylan-munson, could you install this branch and confirm it fixes your issue?

```
pip install -U -e git+https://github.com/rht/mesa@ fix_batch_run#egg=mesa
```

**Comment by dylan-munson** [comment]
Hi, I tried running the pip install command but received an error message that git checkout -q fix_batch_run did not run successfully, so I am unable to try.

**Comment by dylan-munson** [comment]
Sorry, I made a mistake somewhere and was actually able to install.  This did indeed fix the problem, thank you!

**Comment by rht** [comment]
I will add a test case when I have the time. For now, this is a hotfix so that people's `batch_run` is back to be running again.

**Comment by rht** [comment]
> Sorry, I made a mistake somewhere and was actually able to install. This did indeed fix the problem, thank you!

@dylan-munson  thank you for testing.

**Comment by EwoutH** [comment]
Do we need a backport to 2.3 branch and a new 2.3.x. patch release?

**Comment by rht** [comment]
Ah, right, for 2.3.x only, since the `_steps` is new since 2.3.0.

**Pull request merged**
