### PR TITLE
v0.8.3 release notes & version update

### PR DESCRIPTION
**Pull request by jackiekazil**
This is just an update of the history file and version number on Mesa.
Reviewing all the things that were done since the last release made me smile. :-) There are so many awesome things that happened. Thank you everyone your contributions!! 

Can someone do a review of the history file and make sure that I haven't missed anything that changed since v0.8.2 (Gila Bend)?

Everything that is a part of this release has been tagged with the Hayden milestone. 
https://github.com/projectmesa/mesa/milestone/16

### CODE REVIEW

**Comment by dmasad** [comment]
I've merged in a few outstanding PRs today, so we should probably update the history to match.

**Comment by jackiekazil** [comment]
@dmasad done.... can I get a thumbs up from you or someone else?

**Comment by dmasad** [comment]
LGTM

**Comment by jackiekazil** [comment]
This was pushed to PYPI - https://pypi.python.org/pypi/Mesa/0.8.3

**Pull request merged**
