### PR TITLE
viz: stop running and disable buttons when model.running is False

### PR DESCRIPTION
**Pull request by wang-boyu**
This PR stops calling `model.step()` from the frontend when `model.running` is `False`. Play and step buttons are also disabled.

### CODE REVIEW

**Review by Corvince — APPROVED** [review]

**Comment by Corvince** [comment]
Looks good to me!

**Comment by EwoutH** [comment]
How/when should/can I use this?

**Comment by wang-boyu** [comment]
Oh sorry I should've provided more context.

The current solara viz keeps calling model.step() and updating plots, even when the model stops itself, in models such as the Schelling example:

```python
def step(self):
    # model logic
    ...
    if self.happy == len(self.agents):
        self.running = False
```

This PR stops the frontend when model.running becomes False, and disables the play and step buttons.

**Review by EwoutH — APPROVED** [review]
Awesome, sounds like an useful feature!

**Comment by EwoutH** [comment]
@quaquel want do you think about the whole `self.running` concept?

**Comment by quaquel** [comment]
> @quaquel want do you think about the whole self.running concept?

A currently underdeveloped feature that needs to be implemented better. It is used with `self.run_model`, which is also strange and creates a typing mess. I. have looked at it a few times without coming up with a clean solution. My rough idea is to have some `stopping_condition` callable, which can be parameterized by arguments to `self.run_model`, and when the stopping condition becomes true, `self.running` is automatically set to false. By default this `stopping_condition` might simply be tied to `steps` and be parameterized with `n` for the number of steps. If this `stopping_condition` is a method on `Model`, you would have a meaningful default while making it user-extendable,

**Comment by rht** [comment]
Minor question:

I forgot about the old behavior of SolaraViz. Which one is it:
1.has it been this way but changed in #2299, then this PR fixes it
2. the bug has always been there even before #2299

This only affects whether it should be communicated as a bug fix or a new feature in the release note.

**Review by rht — APPROVED** [review]

**Comment by wang-boyu** [comment]
It's probably included in https://github.com/projectmesa/mesa/pull/2263/? I didn't try it but there were some usages of `model.value.running`. It was replaced with `playing.value` in https://github.com/projectmesa/mesa/pull/2282.

**Comment by wang-boyu** [comment]
Merged! Pls feel free to change the label if anyone thinks there's a better one.

**Comment by rht** [comment]
It's a bug fix. The old JupyterViz does check the model.running: https://github.com/projectmesa/mesa/blob/7addec3e008d7c5d66aba131c50b55cd31ba18ab/mesa/experimental/jupyter_viz.py#L231-L234.

**Pull request merged**
