### PR TITLE
Remove duplicate ."virtual_documents"

### LINKED ISSUE #2412: file duplication
**Describe the bug**
reads the docs is producing a folder called .virtualdocuments that duplicates the tutorial notebooks

**Expected behavior**
no duplication of files

**To Reproduce**
Do a read the docs build locally 

**Additional context**
Identified in #2411

### PR DESCRIPTION
**Pull request by EwoutH**
These were added in #2411, but are duplicate and not needed. Closes #2412.

### CODE REVIEW

**Comment by quaquel** [comment]
Have you confirmed yourself or with @tpike3 that these files can safely be removed? If so, go ahead and merge this.

**Comment by EwoutH** [comment]
Nope, unfortunately Tom hasn’t gotten back yet.

That PR was merged under severe time pressure, so we let some normally unacceptable changes go in. It’s fine to play that card once in a while, but then I expect you to clean up after yourself. If that doesn’t happen I will do it (and be more hesitant about approving such PRs in the future).

To be honest this feels the same of the duplicate Readmes of a while ago. Making clean commits is important, and carefully reviewing your changeset. I’m 90% sure they’re just artifacts generated in some process, and if we really need to keep two identical notebooks and maintain those, I want to see a very well argued PR that goes through a normal review process.

Because we’re not talking about two lines of docstring here, but 1000+ lines of code and a new root folder.

**Comment by quaquel** [comment]
> To be honest this feels the same of the duplicate Readmes of a while ago.

I still don't understand what was going on there, mainly because on my machine and in the diff, there was no file duplication. My hunch is that git did not properly record the file renaming and was instead seen as the adding of a new file and the removal of the old file. File removal on git can result in orphaned files on other systems. I have had this problem myself with a couple of the reorganization PRs recently.

**Comment by EwoutH** [comment]
Yeah git is weird sometimes, no worries.

**Pull request merged**
