### PR TITLE
Update travis python versions

### PR DESCRIPTION
**Pull request by Corvince**
Update to include Python 3.9 testing on travis.

Since we already removed support for Python 3.5 earlier, we don't need to juggle around with python versions for black and I now added black as a developer tool/install in `setup.py`.

### CODE REVIEW

**Comment by jackiekazil** [comment]
@Corvince can you resolve the conflict on this?

**Comment by Corvince** [comment]
@jackiekazil done

**Comment by rht** [comment]
Then there is no slot left for PyPy?

**Comment by rht** [comment]
Also, there is this [HN comment](https://news.ycombinator.com/item?id=24837142) on the problem of using 3.9 for scipy stack. Not sure if it has been fixed.

**Comment by Corvince** [comment]
@rht 
Mesa uses travis mainly for testing incoming changes. The question being asked: "Does this code change still pass our tests for the supported python versions and is it formatted correctly?" 

We can't answer that question for PyPy, because the installation of PyPy itself fails on travis. Once this is resolved I am very happy to include it on travis. May I ask why you think this PR leaves no slot for PyPy?? 

But we can answer that question for Python 3.9. Does this mean Python 3.9 is recommended to use right now? No, but we know that it doesn't fail. (but thanks for the HN comment, I wasn't aware of this)

**Comment by rht** [comment]
> May I ask why you think this PR leaves no slot for PyPy??

I don't have a source to back this, but IIRC Travis only has 4 slots of free instances for FOSS projects.

> Does this mean Python 3.9 is recommended to use right now? No, but we know that it doesn't fail. (but thanks for the HN comment, I wasn't aware of this)

We should wait until 3.9.1 in December.

**Comment by rht** [comment]
This issue can be closed.

**Pull request closed without merging**
