### PR TITLE
Convert README.rst to README.md via pandoc

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by rht** [comment]
This breaks the Sphinx build, because it needs README.rst. It means I have to convert all the remaining RST files in 1 PR.

**Comment by rht** [comment]
It seems to work without having me converting the docs to .md. However, this PR depends on #1870 to be merged.

**Comment by tpike3** [comment]
> It seems to work without having me converting the docs to .md. However, this PR depends on #1870 to be merged.

Does it depend on #1870, it looks like it supersedes it?

**Comment by rht** [comment]
It has a commit from #1870, but that commit will disappear once I rebase. I am building this PR over #1870 to prevent a redo due to merge conflict.

**Comment by rht** [comment]
Rebased. This PR is ready.

**Review by tpike3 — APPROVED** [review]
LGTM--- Thanks @rht!!

**Pull request merged**
