### PR TITLE
agents can be removed and added during Scheduler.step()

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
See [issue 584](https://github.com/projectmesa/mesa/issues/583) for previous discussion.

It does what the title says, however we were wondering if maybe some assumptions are now broken?

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
Should I worry about the Travis CI build failing? I seems to be style-related?

**Comment by Maarten-vd-Sande** [comment]
It now fails because the actual model.random is not (yet) implemented. I didn't see your comment about renaming it to iter_agents. I'll change it, but I think maybe buffer is actually more true.
I moved it to the BaseScheduler, because then I did not have to reference to the model and the agents, seemed better to me. Idk if you like it.

The function is a generator function, I made a small example of how it works, and that the current implementation works in our example:
```
def generator(agents):
    agent_keys = list(agents.keys())
    for key in agent_keys:
        if key in agents:
            yield agents[key]

agents = {1:'Maarten', 2:'Corvince', 3:'Dmasad'}

for agent in generator(agents):
    print(agent)
    if agent == 'Maarten':
        agents[4] = 'JackieKazil'
    if agent == 'Corvince':
        agents.pop(3, None)

>>> Maarten
>>> Corvince
```

**Comment by Maarten-vd-Sande** [comment]
Or did you mean that the new agents are not stepped in the timestep they are added? That is true!

**Comment by Corvince** [comment]
Hey there, thanks for the update. Don't worry about the name, that's fine. 

And yeah I meant the latter, but I was just misinterpreting your docstring. 
I read it like "...allows to remove agents (new functionality!) and add agents (new functionality!)". But it just states that we can remove and add agents and the latter isn't new, but of course correct. 

From a theoretical viewpoint it is quite interesting that we want to remove agents immediately, but add them only to the next time step. But yes, that is pretty much what you would expect. 

And with this implementation, if one wants to remove them in the next step you can use simultaneous activation and if you immediately want to step them you can just call their step() function outside the scheduler. 

And of course don't worry about the travis build failing, I will only merge this after #572 is merged.

**Pull request merged**
