### PR TITLE
Remove mesa.flat namespace

### PR DESCRIPTION
**Pull request by rht**
This doesn't seem to be used as often as the current simple namespace.

### CODE REVIEW

**Comment by EwoutH** [comment]
Agreed, but I'm afraid this is a 3.0 ticked since it's breaking.

**Comment by EwoutH** [comment]
2.3 is released, so we can start with 3.0 development work, including moving this PR forward!

**Comment by rht** [comment]
Can this be merged ASAP? This is a straightforward PR.

**Review by EwoutH — APPROVED** [review]

**Comment by EwoutH** [comment]
Can we add a deprecation message to the 2.3 branch?

**Comment by rht** [comment]
I don't think anyone has ever used this namespace. It's not documented, and was already voted out in the past.

**Comment by EwoutH** [comment]
But adding a deprecation warning should be straightforward and is best practice.

**Comment by rht** [comment]
Needs to fix the CI tests ASAP. The deprecation warning is not going to be a part of this PR. See #2133, which fixes the tests.

**Comment by EwoutH** [comment]
Check green, thanks for this PR and merging!

**Pull request merged**
