### PR TITLE
Batch runner redux

### PR DESCRIPTION
**Pull request by tpike3**
### Summary of Changes:

I recommend after anticipated further modifications we do a version push. My timing on this is to give you time to review and then discuss at next Dev Session  6 August.

**BatchRunnerMP**

- removed pathos (unnecessary as unorderedmap in pathos is same as multiprocessing)
- refactored so compatible with Windows, Mac and Linux OS

**Batchrunner**

- add two functions and updated run functions so users can call model datacollectors
- get_collector_model: returns dictionary of dataframes for datacollector model reporters
- get collector_agents: returns dictionary of dataframes for datacollector agent reporters
  (key for dictionaries is unique parameter variation with iteration number)

**DataCollector**

- expanded to allow more collection types to be passed in model reporter (agents are handled internally so I did not think it was needed). This was necessary because lambda cannot be used at the model level for multiprocessing

      key_name: class attribute
      key_name: function (e.g schedule.get_agent_count)
      key_name: lambda function
      key_name: [function, [param1, param2]]

**Tutorial**

- Updated tutorial to include to different batchrunner collection examples (1) From batchrunner directly (2) From datacollector in model stored in dictionary

### CODE REVIEW

**Comment by tpike3** [comment]
Closing to fix lack of codecov report

**Comment by Corvince** [comment]
Sorry for not reviewing this already. Is there a new PR coming?

**Comment by Corvince** [comment]
Also: There seems to be quite a lot unrelated file changes. Could you somehow separate the batchrunner changes from the rest?

**Comment by tpike3** [comment]
@Corvince  Thanks! As you pointed out there really is two areas of fixes - (1) Batchrunner the which includes includes changes to datacollection because of their interdependencies, a batchrunnerMP test module, and documentation update. (2) The example folders, these were all failing to run because of import path issues. Which I thought was weird so I may be misunderstanding something, but I got them running to make sure all the travis checks pass, but then Travis did not run and I did not get a codecov report. I am trying figure out why, but I will try to seperate them and get the travis check and codecov working for cleaner pull requests.

**Comment by tpike3** [comment]
@Corvince I found the Travis test (thanks to your conversation with @rht).  I will fix the failures and that should get the codecov report and then I will do the pull request again

**Pull request closed without merging**
