### PR TITLE
SolaraViz Updates

### PR DESCRIPTION
**Pull request by Corvince**
Some more work on the SolaraViz Frontend. Highlights

1. Much better docstrings
2. Removed `make_text` function. It was used like `make_text(renderer)`, but now you can use `renderer` directly as a component
3. Merged Play/Pause button and disabled step button while model is running
4. Reorganised the Sidebar to look like this
image

### CODE REVIEW

**Review by EwoutH — APPROVED** [review]
Looks great!

Not directly for this PR, but are you still supporting a name change (we were considering `ModelExplorer` right)?

**Comment by rht** [comment]
> Removed make_text function. It was used like make_text(renderer), but now you can use renderer directly as a component

Which objects are allowed/not allowed? `make_text` was specific to string objects. Would float work?

**Comment by rht** [comment]
I didn't voice this concern in the past: but before this PR, the reset button was dangerously close to the play button, that people could accidentally fat-fingered it. But now it seems safer.

**Comment by rht** [comment]
One of the tests in test_solara_viz.py failed.

**Comment by Corvince** [comment]
> Which objects are allowed/not allowed? `make_text` was specific to string objects. Would float work?

Good question, I don't know. I would guess only strings work, but I will test this out

**Comment by rht** [comment]
In this case, it's fine since I haven't provided any change requests, so the agreement is implicit, but in the future, I'd appreciate if the visualization PR gets merged when I explicitly approve, since @EwoutH hadn't dev-ed in the viz area yet.

**Comment by Corvince** [comment]
Sounds fine to me!  But yes, since you already replied without any change requests I thought you are fine with the changes. And appreciated the heads-up to the failing test

**Pull request merged**
