### PR TITLE
Only set model_parameters once

### PR DESCRIPTION
**Pull request by Corvince**
## Summary
While working on a seed widget I saw a major bug in solara viz. Model_parameters get reset on every model reset. This is pretty serious and I think we need another bug release soon. 

## Bug / Issue
**Describe the bug**
Hitting "reset" in the ui resets the model, but also resets the model_parameters to their initial value. 

**To Reproduce**
Run Schelling example. Reduce agent density. Hit reset. Works as expected. Hit reset again. Density is now restored. 

## Implementation
Use solaras `use_effect` to initialize model_parameters only once.

[screen-capture.webm](https://github.com/user-attachments/assets/2bb82a8e-5552-40ca-9840-e4580a2c48aa)

### CODE REVIEW

**Review by quaquel — APPROVED** [review]
Would there be a way to test this behavior as part of our unit tests?

**Comment by quaquel** [comment]
That is a serious bug and something that had been nagging me but did not investigate yet. Great you spotted it and fixed it.

I will put some effort on the logging stuff because that would have helped in spotting this earlier.

**Review by EwoutH — APPROVED** [review]
Thanks for catching it and fixing it. I will do a backport + release as soon as you merge.

Anything else we'll want to include in the backport?

**Comment by Corvince** [comment]
> Would there be a way to test this behavior as part of our unit tests?

Not right now, at least not in an easy way. This would require a integration test that combined solara viz, ModelController and ModelCreator. We don't have that yet

**Comment by EwoutH** [comment]
3.0.3 with this fix is released.

**Pull request merged**
