### PR TITLE
Raise exception when pos is out of bounds in Grid.get_neighborhood

### PR DESCRIPTION
**Pull request by Tortar**
By https://github.com/projectmesa/mesa/pull/1476#issuecomment-1301238002

### CODE REVIEW

**Comment by rht** [comment]
Since this is a breaking change, we need to wait until we are aiming at Mesa 2.0.

**Comment by Tortar** [comment]
yes, no problem, thank you for the reminder!

**Comment by rht** [comment]
I'm about to merge this since we are going for 2.0, but I wasn't able to force push https://github.com/Tortar/mesa/tree/patch-16, unlike in other PRs. Not sure if maintainer edit is disabled, or if it is due to something else. Can you rebase your branch?

**Comment by rht** [comment]
It seems GH is buggy right now, since I can't even push to my own fork.

**Comment by rht** [comment]
Nvm, I force-pushed.

**Pull request merged**
