### PR TITLE
Use PyData config for RTD colorscheme

### PR DESCRIPTION
**Pull request by rht**
See https://github.com/readthedocs/sphinx_rtd_theme/issues/1496.

### CODE REVIEW

**Comment by rht** [comment]
It works: https://mesa--2207.org.readthedocs.build/en/2207/howto.html.

**Comment by EwoutH** [comment]
image

For me the only thing that looks different is the code coloring scheme in dark mode. In light mode it's completely identical.

Is that the intention of this PR?

**Comment by EwoutH** [comment]
To be brutally honest: I like the current color scheme better.

**Comment by rht** [comment]
It's not my opinion, it's that gruvbox is the most popular colorscheme at least in the Vim space (not sure about the other editors): https://vimcolorschemes.com/i/top.

**Comment by EwoutH** [comment]
Let's do a vote!

First, the light color scheme:

- 🎉 = Keep the current code color scheme (left)
- 🚀 = Use the new code color scheme (right)
- 👀 = Don't care / indifferent / both good

Screenshot_475

**Comment by EwoutH** [comment]
Then, the dark color scheme:

- 🎉 = Keep the current code color scheme (left)
- 🚀 = Use the new code color scheme (right)
- 👀 = Don't care / indifferent / both good

Screenshot_474

**Comment by EwoutH** [comment]
It's 5-2 on the light and 4-3 on the dark format, on keeping the current color scheme. I think that concludes that it's preferred to keep the current one?

**Comment by rht** [comment]
What a strange crowd.

**Pull request closed without merging**
