### PR TITLE
Update Pipfile to use Python 3.9

### PR DESCRIPTION
**Pull request by EwoutH**
Updates the Pipfile to use Python 3.9 and updates the Pipfile.lock correspondingly. These files are mainly used for finding bugs/issues were you want to ensure an identical environment, and in that case it's nice to have an up to date, but stable one. Python 3.9 seems like a nice balance at this point.

### CODE REVIEW

**Comment by jackiekazil** [comment]
I merged the github action which updates the piplock. can you just submit the python update and I will merge that?

**Comment by EwoutH** [comment]
Hi! I think it's still good to update both simultaneously (as done in this PR), otherwise a incompatible pipfile.lock will be present. Then on December 1st the Github Action will open a PR that updates the pipfile.lock further.

**Comment by EwoutH** [comment]
@jackiekazil I didn't noticed the Pipfile.lock was already updated with #1080. Seems like it's working correctly!

I now updated the Pipfile, the update-pipfile workflow and the Pipfile.lock to Python 3.9. This PR should now contain all necessary changes.

**Comment by EwoutH** [comment]
@tpike3 It's a bit of work to rebase and regenerate the Pipfile each time. Can we get this in?

**Comment by jackiekazil** [comment]
LGTM

**Comment by tpike3** [comment]
Thanks @jackiekazil !!!

**Pull request merged**
