### PR TITLE
Merging the modular server

### LINKED ISSUE #79: Modular visualization JavaScript in the HTML file or separate?
Right now, the JavaScript to render each visualization module is included in the template HTML file as a script tag. This means that on the final page, each visualization div has its own separate script tag. This is ugly, and also not very standard for web development. But none of the alternatives are great:

- Include the code in a separate JavaScript template. This means that each module needs at least two external files: an HTML template, and a JavaScript template.

- Have users write template code directly in Python, as a string. This seems non-ideal, since it involves writing JavaScript in a Python environment, as a long and hard-to-debug string.

- Other ideas?

### PR DESCRIPTION
**Pull request by dmasad**
This is a major commit, merging in the modular visualization server. It includes the server itself, a few modules (especially the CanvasGrid), and rewrites the example model visualizations to work with it. It also fixes a few other miscellaneous bugs. In particular, this closes #79, #83, #49, #35, and possibly some other ones I'm missing.

### CODE REVIEW

**Comment by jackiekazil** [comment]
Holy crap this is big.
@dmasad So, I was going through this and there are a lot of conflicts w/ master. 
Questions... 
* Can I assume that everything in this would trump over master?  
* Did you run the tests locally with these changes?

**Comment by dmasad** [comment]
Yes, it passes all the tests. And it mostly breaks backwards-compatibility with the visualization -- it shouldn't have an effect on the models themselves.

I'm not seeing a way to view all the conflicts on GitHub, but if you want to go over them together for verification, we can do that.

**Comment by jackiekazil** [comment]
I feel like I have never seen this file in a repo before that I can remember.... not to say that it is a problem, but what is it? Is is supposed to be checked in? https://github.com/projectmesa/mesa/tree/clean_modules.79/examples/EpsteinCivilViolence/.ipynb_checkpoints

**Comment by dmasad** [comment]
Ugh those are the chaff that the IPython Notebook leaves behind, and we should exclude those from being checked in.

**Comment by jackiekazil** [comment]
:+1:

**Comment by jackiekazil** [comment]
I am going to close this in lieu of #126 since you check that one already.

**Pull request closed without merging**
