### PR TITLE
 #769: Fix parameter order in initializing SingleGrid object

### PR DESCRIPTION
**Pull request by Mat-pa**
Parameter order should be width, height, torus according to https://mesa.readthedocs.io/en/master/apis/space.html

### CODE REVIEW

**Comment by rht** [comment]
Nice catch. I grepped for the same pattern and found the mistake in one more file:
```
$ rg 'singlegrid\(height'
examples/schelling/model.py
53:        self.grid = SingleGrid(height, width, torus=True)

examples/pd_grid/pd_grid/model.py
34:        self.grid = SingleGrid(height, width, torus=True)
```

@Mat-pa can you update the PR to include the fix for pd_grid as well?

**Comment by Mat-pa** [comment]
@rht Sure, done :)

**Comment by rht** [comment]
LGTM. cc: @Corvince

**Comment by dmasad** [comment]
Looks good, thanks!

**Pull request merged**
