### PR TITLE
perf: faster is_integer function for common cases

### PR DESCRIPTION
**Pull request by Tortar**
Changing the `is_integer` function like this __getitem__ is faster(1.3x) to access a position as `grid[x, y]`

### CODE REVIEW

**Comment by rht** [comment]
Black lint failed.

**Comment by rht** [comment]
You need to rebase your branch for the Black stuff. Should be fixed in main already.

**Comment by rht** [comment]
Make sure the commit message uses imperative sentence.

**Comment by rht** [comment]
I think we need to add a comment explaining why we define the integer types, i.e. for perf purpose. Also, needs a rebase.

**Comment by Tortar** [comment]
I added a comment and rebased. But maybe I messed a bit the history, I don't find a way to squash the commits right now. Can you do it?

**Pull request merged**
