### PR TITLE
Bank reserves example

### PR DESCRIPTION
**Pull request by cgit2017**
This is related to ticket #431

### CODE REVIEW

**Comment by TaylorMutch** [comment]
@cgit2017 This is really good and very well documented - well done! Could you address the Travis CI build failures? It looks like the flake8 tests are failing. Could you run the flake8 test command outlined in the [contributor's guide](https://github.com/projectmesa/mesa/blob/master/CONTRIBUTING.rst#testing-and-code-standards) and update this PR with those changes? It would also be great if the `Update Readme.md` commits could be squashed into one.

**Comment by cgit2017** [comment]
@TaylorMutch Thank you. I've updated the fork so that all the flake8 tests should pass now. It looks like the only problem was __init__.py. I also uploaded a new Readme.md file as a single update. Is it best to create a new pull request?

**Comment by TaylorMutch** [comment]
@cgit2017 the main reason I bring it up is to help keep the git history a bit simpler when merging  this is. I could also just squash all the commits from this PR into one, which may be simpler. Any objections? @jackiekazil?

**Comment by cgit2017** [comment]
@TaylorMutch The flake8 test is still failing on __init__.py because there is a blank line in the file. I can't figure out how to upload a blank file to the repository. Any advice?

**Comment by cgit2017** [comment]
@TaylorMutch @jackiekazil The checks all passed. Is it necessary to include a blank __init__.py file? I couldn't figure out how to upload one because GitHub would ignore a blank file, but flake8 wouldn't pass a file with a blank line.

**Comment by cgit2017** [comment]
@TaylorMutch is there anything else I need to do for this to be merged? just waiting for further guidance. sorry if you are waiting on me, I'm new to GitHub and may have missed something obvious.

Thanks

**Comment by TaylorMutch** [comment]
@cgit2017 sorry, I've been busy this last week (moving jobs).

When I have a moment, what I'll do is I'll squash your commits into one commit so that when it gets merged in, all the changes you made here will be reflect in one fell swoop.

Thanks for your patience!

**Comment by TaylorMutch** [comment]
@cgit2017 Thanks! You're good to go!

**Pull request merged**
