### PR TITLE
Remove extraneous spaces from docstrings in modules 2

### PR DESCRIPTION
**Pull request by Tortar**
Some of the modules were missed in #1493, sorry

### CODE REVIEW

**Comment by rht** [comment]
Just to make sure, are those the remaining ones, and no more?

**Comment by Tortar** [comment]
Actually need to check the other folders apart from the mesa one

**Comment by Tortar** [comment]
ok, now it's done in all the folders

**Comment by rht** [comment]
LGTM

**Comment by EwoutH** [comment]
It might be useful to adopt a style guide for docstrings. Common ones:

- Strict [PEP 257 Docstring Conventions](https://peps.python.org/pep-0257/)
- The [Google style guide](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings)
- The [NumPy style guide](https://numpydoc.readthedocs.io/en/latest/format.html)
- The [Sphinx docstring format](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html)

For example, the NumPy style guide maintains a white line before the last `"""`, while the others do not.

**Comment by Tortar** [comment]
I'm surely in favor of a style guide and I prefer without blank lines :-)

**Comment by jackiekazil** [comment]
@EwoutH can you start that topic as a discussion so it doesn't get lost in this PR

**Comment by rht** [comment]
I wonder if the white line convention can be enforced in a linter? I'm saying it here instead of in the discussion thread that @EwoutH is going to start, or else I might forget to say this.

**Comment by EwoutH** [comment]
> @EwoutH can you start that topic as a discussion so it doesn't get lost in this PR

Good idea, here we go: https://github.com/projectmesa/mesa/discussions/1499

**Pull request merged**
