### PR TITLE
Fix broken monospace links

### PR DESCRIPTION
**Pull request by fkohrt**
Nested inline markup – here: a combination of [inline literals] and [embedded URIs] – is currently [not supported] by reStructuredText. Now using a substitution reference defined with the "replace" directive.

[inline literals]: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#inline-literals
[embedded URIs]: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#embedded-uris-and-aliases
[not supported]: https://docutils.sourceforge.io/FAQ.html#is-nested-inline-markup-possible

### CODE REVIEW

**Comment by rht** [comment]
I tested by looking at https://github.com/fkohrt/mesa/blob/patch-1/docs/tutorials/intro_tutorial.rst. It doesn't seem to be working.

**Comment by fkohrt** [comment]
> It doesn't seem to be working.

At least not in GitHub. But using a public [reST](https://livesphinx.herokuapp.com/) [viewer](http://rst.aaroniles.net/) I get the indented result for the changed source.

**Comment by rht** [comment]
OK, I tested at https://livesphinx.herokuapp.com/, and it seems to be working. Merging now. And will check the RTD version as a follow up. Thank you for the fix!

**Comment by rht** [comment]
It works! But the `mesa.DataCollector` is not in blue, and so people are actually less likely to know that it is clickable. I think we should just remove the monospace code quote and just do mesa.Datacollector.

**Comment by rht** [comment]
@fkohrt do you want to do a PR making them blue (remove the code quote)?

**Comment by fkohrt** [comment]
Yes, see #1388.

**Pull request merged**
