### PR TITLE
updated epstien_civil_violence.py file in https://github.com/jayash1973/mesa/tree/main/mesa/experimental/devs/examples

### PR DESCRIPTION
**Pull request by jayash1973**
updated epstien_civil_violence.py file in https://github.com/jayash1973/mesa/tree/main/mesa/experimental/devs/examples with new solara visualizations and with use of new ABMS simulator

### CODE REVIEW

**Comment by EwoutH** [comment]
Looks great, but please open a PR to mesa-examples. We want to move these to mesa-examples.

I updated https://github.com/projectmesa/mesa/issues/2191 to be (hopefully) more clear.

> I would really recommend you to works towards atomic commits. Here's an excellent article about it:
> 
> * [Atomic commits will help you git legit.](https://www.pauline-vos.nl/atomic-commits/)
> 
> Thinking in atomic commits might help you organizing and structuring such a project way better.

Have you read this yet?

**Comment by jayash1973** [comment]
> Thanks for the effort, but please open a PR to mesa-examples. We want to move these to mesa-examples.
> 
> I updated #2191 to be (hopefully) more clear.
> 
> > I would really recommend you to works towards atomic commits. Here's an excellent article about it:
> > 
> > * [Atomic commits will help you git legit.](https://www.pauline-vos.nl/atomic-commits/)
> > 
> > Thinking in atomic commits might help you organizing and structuring such a project way better.
> 
> Have you read this yet?

i have read this, didnt understand much but will get it soon with practice.

i was asking if the changes i have made can be accepted or should i just copy the original file to the mesa-examples repository(the original file has some issues as it did not use sola visualization and there were some issues with its code too).

**Comment by jayash1973** [comment]
> Thanks for the effort, but please open a PR to mesa-examples. We want to move these to mesa-examples.
> 
> I updated #2191 to be (hopefully) more clear.
> 
> > I would really recommend you to works towards atomic commits. Here's an excellent article about it:
> > 
> > * [Atomic commits will help you git legit.](https://www.pauline-vos.nl/atomic-commits/)
> > 
> > Thinking in atomic commits might help you organizing and structuring such a project way better.
> 
> Have you read this yet?

hey i will fix the issue #2191 tomorrow i think i should get a bit more familiar on how to use mesa

**Comment by EwoutH** [comment]
> i was asking if the changes i have made can be accepted or should i just copy the original file to the mesa-examples repository

Both. First copy to mesa-examples, then split in model.py and agents.py, then make minimal modifications to get it to work. Then add visualisation and a Readme.

Each should be (ideally) a single atomic commit.

Having a good IDE (i.e. PyCharm or VS Code) and git client (i.e. GitHub Desktop) helps a lot with the process.

**Pull request closed without merging**
