### PR TITLE
Adding gradient support for agents in GridVisualization

### PR DESCRIPTION
**Pull request by yigitbey**
I've renamed the Color parameter to Colors and made it an array. If the list consists of only one color then the shape is filled only with that color, otherwise it fills it with a gradient created with that colors. 
I've also added an optional parameter called stroke_color. If it is not provided than it becomes the first given color in the colors array.

### CODE REVIEW

**Comment by jackiekazil** [comment]
FYI https://groups.google.com/forum/#!topic/projectmesa/x2En3z9KtWQ

**Comment by jackiekazil** [comment]
@yigitbey so sorry for the delay on this. I was just about to review, but I think the changes from #301 caused a conflict in your PR. Can you merge or rebase those into this branch to resolve?

**Comment by yigitbey** [comment]
Sorry, I was not able to check it yet due to some health issues. I'm recovering now but I won't be able to merge the changes for another week or two.

**Comment by dmasad** [comment]
This looks pretty great! No rush, and get well soon! 

For when you're back -- My concern here is that it seems like ```Colors``` has to be an array here. Can we change it so that it can also accept just a single color parameter, without being wrapped in an array?

**Comment by jackiekazil** [comment]
@yigitbey --- I was wondering what the status of this was & if you are okay? Will you update this?

**Comment by jackiekazil** [comment]
Since there has been no movement on this PR, I am going to comment and close and open a ticket to update and resubmit. This is a great idea, but there is more work to be done on this.

**Pull request closed without merging**
