### PR TITLE
Format Python and Jupyter Notebook files with Black

### LINKED ISSUE #1073: Needs black clean up
See build fail on #1072

### PR DESCRIPTION
**Pull request by EwoutH**
Formats the Python files and Jupyter Notebooks with Black (version [21.10b0](https://github.com/psf/black/releases/tag/21.10b0)).

Closes #1073.

### CODE REVIEW

**Comment by jackiekazil** [comment]
Thank you!

**Comment by EwoutH** [comment]
One issue is, while this updates the Jupyter Notebooks (`.ipynb`) files, it doesn't update the documentation, because that is generated from the reStructuredText (`.rst`) files.

For example, [intro_tutorial.ipynb](https://github.com/projectmesa/mesa/blob/main/docs/tutorials/intro_tutorial.ipynb) is updated but [intro_tutorial.rst](https://github.com/projectmesa/mesa/blob/main/docs/tutorials/intro_tutorial.rst) isn't, so the [Introductory Tutorial](https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html) is still badly formatted.

I see two possible solutions for this:

- When an Jupyter Notebook is modified, regenerate the reStructuredText (ideally automated in CI)
- Generate the docs directly from the Jupyter Notebooks (maybe using [nbsphinx](https://nbsphinx.readthedocs.io/en/0.8.7/)?)

**Comment by jackiekazil** [comment]
Good catch. I am cool with either of these. Is this something you plan on picking up? Can you create a ticket?

**Comment by EwoutH** [comment]
Thanks for getting back to me, for now I created an issue, #1082.

I'm not really experienced with ReadTheDocs or Sphinx, but I might give it a try at some point.

**Pull request merged**
