### PR TITLE
Batch runner params

### PR DESCRIPTION
**Pull request by dcunning11235**
PR that I think satisfies #607 

Added two new utility classes (ParameterProduct, ParameterSampler) for creating parameter combinations, and a base class FixedBatchRunner, which is now the super for BatchRunner, that takes a list(-like) of parameter combinations to run.

### CODE REVIEW

**Comment by jackiekazil** [comment]
@dcunning11235 ty for the PR. We have a few complex issues happening at the moment. We didn't forget about you. It may take us a few days to get to review/discuss this. Hang tight!

**Comment by djfurman** [comment]
looks good! @jackiekazil - review complete; nothing blocking added #676 to backlog for only enhancement I saw.

**Comment by jackiekazil** [comment]
Great!

**Comment by nathanvdlei** [comment]
Hi all! I have been trying to use this logic with multiple variable_parameter entries. For this we use two lists, where one starts at 0.5 and the other starts at 1: 
`variable_params = {'clustering_std': list(np.arange(0.5, 4, 0.5)), 'avoid_fights_factor': range(1, 11)}`
However if we call get_model_vars_dataframe() we seem to find that the wrong list was assigned to the wrong variable. Investigating ParameterProduct and ParameterSampler we have not been able to identify the issue yet. The picture attached demonstrates the possible bug.
Error_Mesa

**Pull request merged**
