### PR TITLE
Fixes #283 - Fixes formatting on viz readme

### LINKED ISSUE #283: Formatting lost in ModularVisualization.md
F'ormatting lost in the section of "Using pre-build modules" of https://github.com/projectmesa/mesa/blob/master/mesa/visualization/ModularVisualization.md

I am not able to trace the history of this bug. (about when the bug appeared)

### PR DESCRIPTION
**Pull request by jackiekazil**
Fixes #283 - Fixes formatting on viz readme

### CODE REVIEW

**Comment by jackiekazil** [comment]
Anyone want to do a quick review?  (It will be the quickest review you have ever done.)

**Comment by jeetu7** [comment]
LGTM. :)
The importance of whitespace.

**Comment by jeetu7** [comment]
@jackiekazil Can you wait for this weekend before releasing new version; I will fix #295 and #296.

**Comment by jackiekazil** [comment]
@jeetu7 sure thing. I will wait for those 2 before releasing an update. 
ty for the review of this. :-)

**Pull request merged**
