### PR TITLE
[WIP] Visualization with Vega

### PR DESCRIPTION
**Pull request by Corvince**
Implement a VisualisationModule for [vega visualizations](https://vega.github.io/vega/) through [altair](https://altair-viz.github.io/).

As always for my work on the front-end an implementation example can be seen for the Schelling example. (The changes to the Schelling example seem bigger than they are because I have enabled auto-formatting with black which e.g. changed ''' to """ and realized too late)

Things to look out for:
 - Linked selections for mouseover of grid and neighbor-chart
 - Slider at bottom that lets you scroll back and forth through time (steps)

Looking for some feedback on the implementation, ideas for next steps.

### CODE REVIEW

**Comment by jdfoote** [comment]
This looks super, super cool. I don't know Vega or Mesa very well (yet) but it seems like a nice next step would be to add support for streaming data rather than just loading the data at the end? (e.g., https://vega.github.io/vega-lite/tutorials/streaming.html)

**Comment by Corvince** [comment]
Thanks for your comment @jdfoote ! 

It actually is already streaming in the data! The specification just creates a named data table, which is then populated during model run time. Currently it just adds all the data, which lets you scroll through time, but increases memory consumption over time. The number of steps to be saved could be limited, but its hard to tell where the limit should be.

But in any case if you want to use the same specification for already generated model data, you would have to only change two lines, the "agents" and "model" data, e.g. to .csv files. I think thats one of the great advantages of Vega. 

If you have any ideas or proposals, please let me know

**Comment by jdfoote** [comment]
Aha - wonderful!

I cloned your repository but I can't get the Schelling example to work - I'm getting:
`ImportError:` cannot import name 'VegaVisualization'`
and I can't figure out why

**Comment by Corvince** [comment]
I guess you try running my example, but having installed the "normal" mesa package.

In the cloned repo folder try running `pip install -e .` (note the dot) to (re-)install mesa with the changes. (the -e switch keeps it updated, even when you change files or switch branches)

**Comment by jackiekazil** [comment]
Discussion during Mesa-Dev meeting... 
* Is this still a work in progress? 
* Should we have Schelling model showing both ways? (with and without vega)

**Comment by Corvince** [comment]
> * Is this still a work in progress?
Yes this is still a work in progress, but will take some more time to finish. It's already here to get some early feedback
> * Should we have Schelling model showing both ways? (with and without vega)
Currently the Schelling model is just my "test bed". I don't have a strong opinion on where a vega visualization could/should be showcased. 
> * Can tests be added for the python code added? Coveralls is failing
Yes and it will make sense to test the Python parts. It's on the todo for this PR. 
However, I don't know how to best test the JS code (currently the entire mesa JS code is untested)

**Comment by Corvince** [comment]
Superseded by #664 and #718

**Pull request closed without merging**
