### PR TITLE
Update Conway example

### PR DESCRIPTION
**Pull request by quaquel**
This adds a solara-based `app.py`, renames the old `app.py` to `st_app.py` for streamlit, updates `readme.md` with correct run instructions, and some minor cleanup and removal of oudated files.

### CODE REVIEW

**Comment by EwoutH** [comment]
Thanks! Could you maybe add screenshots how it looked before and after?

**Comment by quaquel** [comment]
There is no before because there was no solara version.

**Review by EwoutH — APPROVED** [review]
Sliders to change the grid size and initial fraction alive would be nice. You can steal them from: [mesa-examples/examples/conways_game_of_life_fast/app.py](https://github.com/projectmesa/mesa-examples/blob/main/examples/conways_game_of_life_fast/app.py)

Disabling the gridlines and making the agents square would be really improve the viz, see [how it looks](https://github.com/projectmesa/mesa-examples/tree/main/examples/conways_game_of_life_fast) with the PropertyLayer visualisation. But that can be another PR.

Otherwise, looking good, so going to pre-approve. A screenshot of the final viz in the PR description would be appreciated.

**Comment by quaquel** [comment]
> Disabling the gridlines and making the agents square would be really improve the viz, see [how it looks](https://github.com/projectmesa/mesa-examples/tree/main/examples/conways_game_of_life_fast) with the PropertyLayer visualisation. But that can be another PR.

I agree, but changing the marker requires changes in matplotlib.py. Enabling/disabling gridlines is something that probably should become controllabe at the level of `make_space_matplotlib`.

**Pull request merged**
